### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by marksev1** [jasoncoon/esp8266-fastled-webserver#1]
Cool project you have here!

Could you maybe please add MQTT support would be awesome to control the leds via home automation software (Node-red, Domoticz, Openhab etc.). Since MQTT is pretty wide-spread nowadays.

Thanks!

**Comment by jasoncoon** [comment]
Thanks!

I don't know anything about MQTT (yet), but sounds cool.  Looking forward to a pull request from you or someone else that adds it.  :)

**Comment by marksev1** [comment]
I'm not skilled enough, I just do copy-paste "coding" :D, so hopefully someone else adds it :)

Here is some reading material: https://learn.adafruit.com/mqtt-adafruit-io-and-you/overview
