### ISSUE TITLE
Jitter or random resets

### ISSUE THREAD

**Issue by balonchiks** [jasoncoon/esp8266-fastled-webserver#100]
Hi Jason, thanks for your work, really appreciate it. However i am experiencing an issue which is similar to the one described in #85 

I am using a NodeMCU and the latest Arduino IDE, libraries and boards are up to date as well. My setup consists of 65 2812b LEDs. My issue is lots of jitter on your default code. While reading through the previous issues I managed to fix the jitter by setting the interrupt to 1 `FASTLED_INTERRUPT_RETRY_COUNT 1`

However, now there's another issue - the board resets on random (or probably not so random) intervals, and the web interface becomes unresponsive. I think i've also read about this on closed issues.

I have also tried uncommenting this line
`FASTLED_ALLOW_INTERRUPTS 0` and this one `INTERRUPT_THRESHOLD` since the sketch was not compiling with uncommented allow interrupts and without threshold, but no luck - the jitter is still here.

Do you by any chance have any idea on which values should i use to make it work without any crashes and with no jitter? Or is there any other part of the code that should be changed?

Thanks in advance

**Comment by ProdigyBlur** [comment]
Did you specify '2812b' as you LED_TYPE? Also, are you you using a logic shifter for the data pin? I've got 4 of these running with no jitter issues or resets. I'm using D1 Mini's, and the Shield/logic converter as shown in the readme on the main page.

**Comment by balonchiks** [comment]
yep, i tried both 2812b and the default 2811 as the led_type - no difference, and i am not using a level shifter as i would like to make it work fro christmas, and the level shifter would not manage to arrive on time if i order it now..

for now i left it at these values:

```
#define FASTLED_ALLOW_INTERRUPTS 0
#define INTERRUPT_THRESHOLD 0
#define FASTLED_INTERRUPT_RETRY_COUNT 0
```

so it's working fine without any jitter, but the webserver is not responding and esp resets from time to time...

**Comment by balonchiks** [comment]
i think i managed to fix my jitter issue with the forked FastLED from [here](https://github.com/coryking/FastLED). Just replaced it in the libraries folder of arduino and added `#define FASTLED_ESP8266_DMA` before defining fastled.
