### ISSUE TITLE
MQTT Don't know where to put it.

### ISSUE THREAD

**Issue by asm7100** [jasoncoon/esp8266-fastled-webserver#101]

**Comment by asm7100** [comment]
How about make it so it can be uses with MQTT

**Comment by jasoncoon** [comment]
I haven't messed with MQTT on the Arduino, but there is a fork you can try here: https://github.com/awilhelmer/esp8266-fastled-mqtt

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
