### ISSUE TITLE
Won't compile missing file

### ISSUE THREAD

**Issue by ArcadeNut** [jasoncoon/esp8266-fastled-webserver#102]
it appears this user_interface.h file is not included in the download.

extern "C" {
#include "user_interface.h"
}

**Comment by jasoncoon** [comment]
I think that file is provided by the ESP8266 Arduino core.  What error are you getting?  Can you include the compiler output?  Tried commenting out those lines?

**Comment by ArcadeNut** [comment]
sorry, was my issue.  the issue was I needed to create a Secrets.h,  I didn't see the user_interface.h and thought I needed it.

thanks
