### ISSUE TITLE
Control Over Internet

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#103]
Do you know how to make this accessible from away from home?

**Comment by ArcadeNut** [comment]
add a couple lines of code to make the IP static or in your router assign the DHCP IP address to your device os it always gets the same IP.

In your router you have to allow the incoming traffic and port it to the IP of the arduino.  but think about the security risks of opening ports.  by default the webserver is running on port 80, so you would route incoming requests on port 80 to the ip of your arduino.

**Comment by awilhelmer** [comment]
Look into my fork changes. You need to have one MQTT Server in the internet.
