### ISSUE TITLE
RESTAP Example call

### ISSUE THREAD

**Issue by patrikkeller** [jasoncoon/esp8266-fastled-webserver#105]
Can you give an example on how to use the RESTAPI:

turn on = http://x.x.x.x/power    ???
change pattern = http://x.x.x.x/pattern ???

**Comment by atatistcheff** [comment]
Here is a script that has a bunch of the URIs in it.  I used tcpdump to see
what the commands were.
https://gist.github.com/atatistcheff/7e49e9915f46b7ed28ddf3670283104b

Alex Tatistcheff
alext@pobox.com

traceroute bad.horse - do it now!
