### ISSUE TITLE
Alexa On/Off

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#106]
Anyone know how to add Alexa ON/OFF to this?

**Comment by atatistcheff** [comment]
Create a custom Alexa skill.  Check this out
https://forums.developer.amazon.com/questions/94078/alexa-skill-calling-local-url.html

Alex Tatistcheff
alext@pobox.com

traceroute bad.horse - do it now!

**Comment by awilhelmer** [comment]
I created a Alexa skill and modified this lib to communicate via MQTT.

Fork: https://github.com/awilhelmer/esp8266-fastled-mqtt
Alexa MQTT Skill: https://github.com/awilhelmer/alexa-mqtt-skill

But it isn't a smart home skill. You have to say something like "Alexa, say broker <device> <command> <params>"
You can change the keyword "broker". Device, command and params are configurable in the skill. The skill will send a MQTT Command to your broker, the ESP is listen to.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
