### ISSUE TITLE
Secrets.h 

### ISSUE THREAD

**Issue by mrlazzy** [jasoncoon/esp8266-fastled-webserver#107]
hi i am having trouble with the new Secrets.h when i connected to esp i get "Not found: /" do i still need to upload Secrets.h with sketch data upload ?

**Comment by apristel** [comment]
Just comment the line out

**Comment by mrlazzy** [comment]
i did 
// create a Secrets.h file with the following:

// AP mode password
const char WiFiAPPSK[] = "";

// Wi-Fi network to connect to (if not in AP mode)
char* ssid = "";
char* password = "";

**Comment by teaker** [comment]
mrlazzy,

You might encounter this issue if you upload the webapp/data file to SPIFFS prior to uploading the sketch itself.  

Try uploading the sketch (esp8266-fastled-webserver.ino) first and then uploading the webapp using Tools --> ESP8266 Sketch Data Upload.

Please let us know if this resolves your problem.

**Comment by mrlazzy** [comment]
it worked ! thanks, also i erased all flash contents since i had previous version of this program.

**Comment by jayjojayson** [comment]
Why is the secret.h file not included in the sketch? There could be a blank file like this and no one has to create the secret.h in the sktech:

// AP mode password
const char WiFiAPPSK[] = "";

// Wi-Fi network to connect to (if not in AP mode)
char* ssid = "";
char* password = "";

I think that would be better solution!
In the evening i will try uploading the sketch (esp8266-fastled-webserver.ino) first and then uploading the webapp using Tools --> ESP8266 Sketch Data Upload

**Comment by FranzKropp** [comment]
Creating the File helped! Thank you @jayjojayson !
