### ISSUE TITLE
Colors are wrong

### ISSUE THREAD

**Issue by kylix34** [jasoncoon/esp8266-fastled-webserver#112]
I select from the picker color "RED" and the led strip solid color turns into "GREEN". Also, "Lava" and "Fire" effects turn the led strip into "GREEN" colors. (I'm using an NodeMCU board)

**Comment by apristel** [comment]
You can change RGB to GRB and it probably will fix it ( or vise versa )

**Comment by kylix34** [comment]
Yessssss!!!! I needed to use GRB. THANKS!
