### ISSUE TITLE
Problem loading webapp

### ISSUE THREAD

**Issue by tbrooks88** [jasoncoon/esp8266-fastled-webserver#114]
Hello,

I am very new to this diy world so please excuse if I'm missing something stupidly simple.

The problem I am running in to is with uploading the webapp using SPIFFS (I think)

-After reading some other posts on this board, I uploaded the esp8266-fastled-webserver.ino to the board first. When I run serial monitor it shows it's connected to my home wifi.
-I then used the 'ESP8266 Sketch Data Upload' tool to upload the webapp from the 'data' folder. The first time it says "are you sure you want to upload an empty data file?". I tried this but then wasn't able to access the web app on my browser.
-I then dragged the 'data' folder (includes folders css, fonts, images, js, etc) into the 'data' folder in the esp8266-fastled-webserver-master folder (which was previously empty), and then sent this file to the wemos using the 'Sketch Data Upload' tool.
-After this when I plug in 192.168.0.187 to my browser it says 'Not found :/'

-using macintosh
-using Wemos D1 mini lite

Thanks for all of your help! I'm really inspired by this board and all of the great projects I've seen out there.

**Comment by jasoncoon** [comment]
Hey, sorry for the trouble.

Does the Serial Monitor show a file listing?

From the root of the project directory, where the ino file is, there should be a data directory.  Inside the data dir should be index.html, css dir, js dir, etc.

Try zipping the files before using the `ESP8266 Sketch Data Upload` tool.  Again from the root dir, run the following command:

`gzip -r data/`

Now inside the data directory you should see index.htm.gz

No problem, sorry for the delayed response!  Looking forward to seeing what you build!

**Comment by tbrooks88** [comment]
Hi Jason!
Thanks again for your help, and sorry about the delay in responding, I've been on a vacation away from my project.

Anyway, after much googling I got the gzip to work and got the data.gz all zipped up. 
When I uploaded this into the SPIFFS and then ran the serial monitor, I got this image.
![screen shot 2019-03-06 at 7 58 57 pm](https://user-images.githubusercontent.com/47617734/53931624-d9f54c00-404a-11e9-943c-a807b2e93d90.png)
However when I then go to 192.168.0.187 it says file not found.

Should I be uploading to the SPIFFS any of the other .gz files I made?
![screen shot 2019-03-06 at 8 01 29 pm](https://user-images.githubusercontent.com/47617734/53931700-217bd800-404b-11e9-830d-9942351742a8.png)

Thanks again!
Trevor

**Comment by jasoncoon** [comment]
Hey Trevor, no problem.  The files in SPIFFS should not be in a data directory, they should be at the root, like this:

```
SPIFFS contents:
FS File: /index.htm.gz, size: 2189
FS File: /css/simple.css.gz, size: 175
FS File: /css/styles.css.gz, size: 62
FS File: /css/bootstrap.min.css.gz, size: 19753
FS File: /css/minicolors.min.css.gz, size: 70763
FS File: /images/atom196.png.gz, size: 5504
FS File: /images/github.ico.gz, size: 1219
FS File: /js/app.js.gz, size: 2576
FS File: /js/jquery-3.1.1.min.js.gz, size: 30140
FS File: /js/simple.js.gz, size: 1864
FS File: /js/bootstrap.min.js.gz, size: 9849
FS File: /js/r-websocket.min.js.gz, size: 1060
FS File: /js/minicolors.min.js.gz, size: 4720
FS File: /edit.htm.gz, size: 4116
FS File: /favicon.ico.gz, size: 1617
FS File: /simple.htm.gz, size: 949
FS File: /wifi.htm.gz, size: 1522
FS File: /fonts/glyphicons.ttf.gz, size: 23399
FS File: /fonts/glyphicons.woff2.gz, size: 18073
FS File: /fonts/glyphicons.eot.gz, size: 20071
FS File: /fonts/glyphicons.svg.gz, size: 26832
FS File: /fonts/glyphicons.woff.gz, size: 23204
```

I'm not sure how/why they are in a data directory.  Your Arduino sketch directory on your computer should look something like this:

![image](https://user-images.githubusercontent.com/3598755/53963856-b5818a00-40b3-11e9-9d77-218fa00c1f4d.png)

**Comment by tbrooks88** [comment]
Hello Jason,
I fixed my directory so it looks just like yours. However when I do the data upload tool it still doesn't go all the way. I think the problem is that the wemos d1 mini lite I am using is too small for the file (my big clue was the "SPIFFS write error: file system full" message.
I imagine I could fix this problem by just getting a regular D1 mini, however do you think I'd be able to make it work by deleting a few of the light programs from the sketch?
Thanks again for all your help!
Trevor

![Screen Shot 2019-03-19 at 5 29 37 PM](https://user-images.githubusercontent.com/47617734/54650644-c98e9980-4a6c-11e9-9067-3329039b6caf.png)

**Comment by Blink515** [comment]
The animations aren't stored in SPIFFS. You'll need to look into getting
rid of the JavaScript libraries from the code and linking to the JavaScript
libraries from a CDN.

I ran into the same issue on my wemos lite as well and was able to use the
steps mentioned above to get things to work.

Keep in mind that this will only work if you are connecting the wemos to
your WiFi network and not using it in AP mode.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
