### ISSUE TITLE
Switches randomly to Pride pattern

### ISSUE THREAD

**Issue by corch1988** [jasoncoon/esp8266-fastled-webserver#118]
Thanks for this awesome project!
I think I managed to setup everything correctly. The Web UI and REST api are working correctly.

Somehow the pattern switches to 'Pride' at random.
Maybe you can help me with a solution to a similar problem you  bumped in to?

**Comment by jordanadania** [comment]
Is autoplay on?

Pride is the 1st pattern. So maybe you're getting some sort of reset.

**Comment by corch1988** [comment]
Sorry for bothering. 
Autoplay was indeed turned on. Everything works perfect now,

Thank you!
