### ISSUE TITLE
help wanted  Nanoleaf Designer... where it is?

### ISSUE THREAD

**Issue by dogson3006** [jasoncoon/esp8266-fastled-webserver#119]
please tell me, how i will find the Nanoleaf Designer or the Nanoleaf Custom Pattern Designer?
If i go to the gui of my node red server i will not found them. only a empty flow 1 is shown. 
if i klick on the import clipboard button, nothing happens.
plz help and sorry for my stupid question and my worse english.
volker

**Comment by jasoncoon** [comment]
I have no idea.  This project doesn't have anything to do with Nanoleaf.

**Comment by jasoncoon** [comment]
OK, I found the nanoleaf fork of this project: https://github.com/NimmLor/esp8266-nanoleaf-webserver

Looks like they forked this project, but didn't enable issues on their fork, which is unfortunate.

You might try asking your question here: https://www.thingiverse.com/thing:3354082/comments
