### ISSUE TITLE
REST API ist stuck

### ISSUE THREAD

**Issue by corch1988** [jasoncoon/esp8266-fastled-webserver#121]
After booting it is possible to send a command over http. After about 10-15 Minutes sending commands does not work. If I navigate to the webpage and wait for it to load (but not changing any settings on the webpage), sending commands over http does work again.

Any thoughts?

**Comment by jasoncoon** [comment]
Any output in the serial monitor?

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
