### ISSUE TITLE
Arduino ESP8266FS tool

### ISSUE THREAD

**Issue by mike2nl** [jasoncoon/esp8266-fastled-webserver#122]
@jasoncoon 
Hi Jason,
a question:
- it is possible that you can make a new version for the Arduino ESP8266FS tool, please?
- because verion 4 is out a while now. It has some upadtes and fixes against 0.2.0 and 0.3.0.

I only can use windows, grrr, becuase it's not my pc. So no linux in any version is installed here.

**Comment by ArtursGailis1995** [comment]
As I am also working on this project (my own fork with more than 30 new effects total) and have access to Linux, you can ask me to do that.

@mike2nl Just tell me what to do and I will compile it or whatever. :)

**Comment by Lustralis** [comment]
The new release working with Win 10 is here:
[https://github.com/esp8266/arduino-esp8266fs-plugin/releases/tag/0.5.0](https://github.com/esp8266/arduino-esp8266fs-plugin/releases/tag/0.5.0)

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.

_(also, try using the new PlatformIO support for building, etc.)_
