### ISSUE TITLE
Homebridge interface

### ISSUE THREAD

**Issue by sorriso93** [jasoncoon/esp8266-fastled-webserver#123]
Hello
I would like to use homekit via homebridge. Is there any possibility to make this kind of integration?
Thks

**Comment by jasoncoon** [comment]
I've never used homekit or homebridge.  I'm sure it's possible, but it's not something I'm interested in or will get around to any time soon.  I'm sure someone out there can help with this, though.  :)

**Comment by denis86111** [comment]
есть продвижение по homebridge?

**Comment by bkonings** [comment]
This might help: https://blog.theodo.com/2017/08/make-siri-perfect-home-companion-devices-not-supported-apple-homekit/

**Comment by NimmLor** [comment]
I guess it is simple with Node-RED, I've controlled the leds via Node-RED but I haven't tested it in combination with homekit, but there is a plugin for it which looks pretty promising.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
