### ISSUE TITLE
Add a config sample file config.h.sample

### ISSUE THREAD

**Issue by Pilooz** [jasoncoon/esp8266-fastled-webserver#124]
Hi,
I discover this project, which is exactly what I was looking for. I was wondering if it could be a good idea to add a config sample file to store configuration values like :
- wifi credentials
- number of LEDs in the strip
- Color order
- Data Pin
- speed
- some default values...
etc...etc... 
As a matter of fact, all configurable values could be written in this file.

This file would be gitted and the installation process will be modified as follow :  
- Copy config.h.sample in config.h
- change values as you need in config.h 
- compile and enjoy

The benefit is that when you need some specific value, you put it in the config.h, which is not in the git repo, so as to keep the git branch clean.
What do you think about that ?

**Comment by jasoncoon** [comment]
Thank you for addressing this!  https://github.com/jasoncoon/esp8266-fastled-webserver/pull/125
