### ISSUE TITLE
No color change

### ISSUE THREAD

**Issue by SharkySK** [jasoncoon/esp8266-fastled-webserver#126]
Hello 
I have followed all steps, pushed and uploaded all the code yet all I get is first LED - white, second LED - green, nothing else. I get the WEB server I can connect and click stuff it says power on and off but doesn't actually do anything could anyone help me troubleshoot? 

I've been having the same issue with other libraries for LEDs as well where it only turned on first 2 LEDs.
I am not using any resistors or capacitors and I am powering the LED strip from the Wemos D1 mini itself.
+5V - 5v pin
DO - D4 pin (i changed the pin in the sketch to D4)
GND - G pin
Any help would be appreciated

**Comment by SharkySK** [comment]
Found out I probably am not even connected to the web server
![image](https://user-images.githubusercontent.com/25453990/55560189-035bd300-56f0-11e9-8544-99d2e7e9e15d.png)

**Comment by jasoncoon** [comment]
Please start with the simpler FastLED examples first, before trying to get this much more complicated sketch working.  :)

**Comment by SharkySK** [comment]
Fixed it, I still get the errors on the WEB server but I guess they are not major errors.
The problem was the Data_pin it was set to D5 which I taught is the number that is set on the board but when I moved the pin to D4 and set the D4 in the sketch it didn't do anything. you were right, I looked at some examples and found out that you should just write the GPIO interpretation so when I wrote "2" instead of D4 I got the lights

**Comment by mukha521** [comment]
Websocket errors are there because websocket functionality is actually commented out in the firmware code and not everywhere in javascript files.
You can ignore everything related to websocket for now ;)
