### ISSUE TITLE
V1.1 vs master

### ISSUE THREAD

**Issue by seanspotatobusiness** [jasoncoon/esp8266-fastled-webserver#13]
Hi Jason. What's the reason that the v1.1 fork is separate from the master? Is it "beta"/unready? Will it be merged into the master eventually or developed separately?

**Comment by jasoncoon** [comment]
Yeah, it's beta, and it's a bit more complicated.  I haven't decided whether I'll merge it to master or not.  Thoughts?

**Comment by jasoncoon** [comment]
As an example, here's the exact same change made in master: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/681c29a8776a40026a26365d3988dedd38526417 and v1.1: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/f04a089fa4e42ddaf2508ea8b2df793f0ab8410e

While the v1.1 code is a bit more complex, adding a new palette selector using the new field support in v1.1 took much less code than in master.

**Comment by seanspotatobusiness** [comment]
Sorry, I'm not really in a position to comment on whether you should merge since I don't know code. My only way to contribute anything is to augment the documentation when I'm able to implement the code into a project myself (which will be a couple of months from now) and maybe report any issues I find.

Does version 1.1 have the feature that allows you to program spatial LED arrangements like your Christmas tree? Will it be trivial to program other arrangements, like, for example, three hexagonal columns?
