### ISSUE TITLE
Connection to Node-RED

### ISSUE THREAD

**Issue by BartoilPerso** [jasoncoon/esp8266-fastled-webserver#133]
Hi there! I'm only just getting started with NodeMCU and Node-RED. I've been poking around with using Node-RED to control multiple strips, multiple devices... Lots of fun!

While it's great to learn through trial and error, I'd love to see if anyone has used Node-RED before with this wonderful software, mostly to get the list of patterns dynamically.

Any comments or suggestions are welcome! I'll try to come back shortly with my findings for people searching in the future, as well.

Thanks!

**Comment by NimmLor** [comment]
Yes, I've done it to make my [Nanoleaf Replica](https://www.thingiverse.com/thing:3354082) compatible with Amazon Alexa.
But I've just hardcoded all patternnames and didn't think of requesting them.
The Node-RED flow can be found in my repository.
https://github.com/NimmLor/esp8266-nanoleaf-webserver

**Comment by BartoilPerso** [comment]
Started to hard code, but I've been bouncing around projects, and have now abandoned NodeRED in favour of Home Assistant. Some good learning along the way!
