### ISSUE TITLE
HC-06 Bluetooth Module

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#134]
I don't have any issues with your webserver. I came here because this is the only place I know to go to get good LED advice.

Do any of you know where I can find a good bluetooth app to run my LEDs?

Sorry and Thank You!

**Comment by anarchking** [comment]
Try Blink app on Android, if your 🍎 trade it in for an Android Tehehe

**Comment by jordanadania** [comment]
Do you mean blynk?

Would a better way to control leds using FASTLed be to use an esp32??
