### ISSUE TITLE
RGBW Support?

### ISSUE THREAD

**Issue by VeniceNerd** [jasoncoon/esp8266-fastled-webserver#139]
Does this library support RGBW strips? I would love to be able to create a gradient going from dark blue at the front of my strip to pure white (using the W LED) on the end of my strip. 

Is this possible?

**Comment by jasoncoon** [comment]
Sorry, but this project uses FastLED, which does not yet support RGBW: https://github.com/FastLED/FastLED/issues/482

**Comment by VeniceNerd** [comment]
Do you happen to know if there are plans by the devs to add that support to FastLED? 

Also, would it be currently possible to create a couple of gradients just using RGB and have presets for them so I can easy switch between them?
