### ISSUE TITLE
how to set up password for AP ?

### ISSUE THREAD

**Issue by mrlazzy** [jasoncoon/esp8266-fastled-webserver#142]

**Comment by jasoncoon** [comment]
https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L69

😄

**Comment by mrlazzy** [comment]
lol thank you for your time Jason. 
is it posible to change my AP name ?

**Comment by jasoncoon** [comment]
😆 No problem!  Sorry for the brevity, got a lot going on at the moment.

https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L279
