### ISSUE TITLE
Reverse animations?

### ISSUE THREAD

**Issue by pauledd** [jasoncoon/esp8266-fastled-webserver#143]
Hi

So I build a nice Moroccan lantern  with a esp8266-fastled-webserver inside, soldered everything nice and tight and assembled the whole thing and then I realized the pattern "fire" burns upside down... :dizzy_face:
Is there a way to "reverse" the animations (I guess it has to do how it iterates through the leds..)?

**Comment by tobi01001** [comment]
Change this line https://github.com/jasoncoon/esp8266-fastled-webserver/blob/d50b4ac19732cc951a077236861d0e09423b52c5/esp8266-fastled-webserver.ino#L1070

from 
`heatMap(HeatColors_p, true); `
to 
`heatMap(HeatColors_p, false);`

and you should be good for your fire animation.

Another option could be to implement a "fire reverse" parameter to be able to change directions via web interface...

For my use case, I use 2 arrays holding the leds and before writing them I copy one to the other.
This way I am able to reverse every effect (and do some other stuff).

**Comment by pauledd** [comment]
Well I would like to go with your 2 arrays method but I am quite lost in the amount of code. 

I guess I have to add another led array, but what then? Can I reverse-for-loop assign the first array to the second like that?:
```
CRGB leds[NUM_LEDS];
CRGB leds2[NUM_LEDS];

for(int i=0;i<NUM_LEDS;i++){
  leds2[NUM_LEDS-i] = leds[i];
}
```

**Comment by tobi01001** [comment]
Yes that's basically it.

you create a second one just linked to the led strip (as you did above). e.g.:


```
CRGB leds[NUM_LEDS];
CRGB leds2[NUM_LEDS];

// in addition you want a reverse parameter:
bool reverse = false;
```
in setup you do
```
// to write the leds2 array to the leds
FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds2, NUM_LEDS); 
// ...
fill_solid(leds2, NUM_LEDS, CRGB::Black);
// ...
webServer.on("/reverse", HTTP_POST, []() {
    String value = webServer.arg("value");
    reverse = value.toInt();
    broadcastInt("reverse", reverse);
    sendInt(reverse);
  });
```

// in loop change
```
if (power == 0) {
    fill_solid(leds2, NUM_LEDS, CRGB::Black);
// ...
```
and before FastLED.show(); you add your copy mechanism:
```
if(reverse) {
  for(int i=0; i<NUM_LEDS; i++) {
    leds2[(NUM_LEDS-1)-i] = leds[i];
  }
}
else
{
  for(int i=0; i<NUM_LEDS; i++) {
    leds2[i] = leds[i];
  }
}
```
Then you add the parameter in Fields.h with:
```
String getReverse() {
  return String(reverse);
}
// and one line to the FiledList Fields:
{ "reverse", "Reverse", BooleanFieldType, 0, 1, getReverse },
```

Did not test it (my code evolved to something completly different). So let me know if it works or you run into problems.

**Comment by pauledd** [comment]
Thanks, I am quite busy at the moment but I am still on it.

**Comment by pauledd** [comment]
Ok, I tried you code, but the compiler complained about 
```
esp8266-fastled-webserver:79: error: 'bool reverse' redeclared as different kind of symbol
 bool reverse = false;   // added
      ^
In file included from /home/p/.arduino15/packages/esp8266/hardware/esp8266/2.4.1/cores/esp8266/Arduino.h:36:0,
                 from /tmp/arduino_build_53394/sketch/esp8266-fastled-webserver.ino.cpp:1:
/home/p/.arduino15/packages/esp8266/hardware/esp8266/2.4.1/cores/esp8266/stdlib_noniso.h:45:6: error: previous declaration of 'void reverse(char*, char*)'
 void reverse(char* begin, char* end);
```

so my guess is "reverse" is already taken somewhere in the code, so I changed every "reverse" in your code to "reverse2"...

Seems to work so far, my fire is now burning upwards and water falling downwards.
Thanks a lot! :blush:
