### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#144]
I'm just curious how difficult it would be for me to make the webpage black background with white text, etc. like dark mode.

If you wouldn't mind pointing me to the first place I might edit something, I should be able to find the rest.

Thank you!

**Comment by ArtursGailis1995** [comment]
Its actually pretty easy.

You have to find this line in *.htm files:
`<link rel="stylesheet" href="css/bootstrap.min.css">`

and replace it with this line:
`<link rel="stylesheet" href="https://bootswatch.com/3/darkly/bootstrap.min.css">`

either using Filesystem Editor or edit in your cketch and re-upload SPIFFS.

Works for me currently, but I am using my own (heavily modified) fork. Should work 99%.

**Comment by jordanadania** [comment]
I don't know how to use the Filesystem Editor. When I found the line in index.htm, it was commented out I believe.

`
  
  `

**Comment by tihoangyeudau** [comment]
> 
> 
> Its actually pretty easy.
> 
> You have to find this line in *.htm files:
> `<link rel="stylesheet" href="css/bootstrap.min.css">`
> 
> and replace it with this line:
> `<link rel="stylesheet" href="https://bootswatch.com/3/darkly/bootstrap.min.css">`
> 
> either using Filesystem Editor or edit in your cketch and re-upload SPIFFS.
> 
> Works for me currently, but I am using my own (heavily modified) fork. Should work 99%.
> 
> Also for other themes you can check out this site: [https://bootswatch.com/3/](url)
> 
> You need to copy the link to bootstrap.min.css as this project is using Bootstrap V3 for UI.

i tried it but not work

**Comment by jordanadania** [comment]
You have to remove <!-- and --!>

**Comment by ArtursGailis1995** [comment]
For it to work you have to connect your NodeMCU to the Internet. If using Local AP mode, it of course will not work.

**Comment by jordanadania** [comment]
that was it. haha. good times.
