### ISSUE TITLE
Fatal exception 28(LoadProhibitedCause)

### ISSUE THREAD

**Issue by GitCode2019** [jasoncoon/esp8266-fastled-webserver#146]
Hi,

after it works for a view minutes, I got the Error on Serial:

ets Jan 8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
⸮⸮
Heap: 44848
Boot Vers: 5
CPU: 80
SDK: 2.2.1(cfd48f3)
Chip ID: 13314078
Flash ID: 1458376
Flash Size: 4194304
Vcc: 65535

SPIFFS contents:
FS File: /js/app.js, size: 12933
FS File: /css/minicolors.min.css, size: 96597
FS File: /js/jquery-3.1.1.min.js, size: 86709
FS File: /css/simple.css, size: 237
FS File: /edit.htm, size: 7887
FS File: /js/minicolors.min.js, size: 15463
FS File: /js/bootstrap.min.js, size: 37045
FS File: /favicon.ico, size: 4286
FS File: /js/r-websocket.min.js, size: 3100
FS File: /css/styles.css, size: 31
FS File: /fonts/glyphicons.eot, size: 20127
FS File: /js/simple.js, size: 6107
FS File: /simple.htm, size: 2279
FS File: /fonts/glyphicons.svg, size: 108738
FS File: /wifi.htm, size: 4190
FS File: /fonts/glyphicons.ttf, size: 45404
FS File: /fonts/glyphicons.woff, size: 23424
FS File: /fonts/glyphicons.woff2, size: 18028
FS File: /images/atom196.png, size: 5469
FS File: /index.htm, size: 10698
FS File: /images/github.ico, size: 6518
FS File: /css/bootstrap.min.css, size: 121093

Connecting to Radio Eriwan!
HTTP web server started
Fatal exception 28(LoadProhibitedCause):
epc1=0x402162f3, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00020500, depc=0x00000000

Exception (28):
epc1=0x402162f3 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00020500 depc=0x00000000

stack>>>

ctx: cont
sp: 3ffffdb0 end: 3fffffc0 offset: 01a0
3fffff50: 00000112 3ffefdd8 3ffefb24 4020986d
3fffff60: 00000000 00000001 3ffefc5c 4020e03a
3fffff70: 00000112 00000008 3ffefc5c 40206034
3fffff80: 3fffdad0 00000000 3ffefda8 40205296
3fffff90: 00000000 00000000 00000001 4020df79
3fffffa0: 3fffdad0 00000000 3ffefda8 4020e008
3fffffb0: feefeffe feefeffe 3ffe8530 40100805
<<<stack<<<

The Network connection worked and I reached the Webserver with my browser and the IP got form the Serial.

Can you help me?
Thank you..

**Comment by jasoncoon** [comment]
What microcontroller are you using?  Can you enable verbose compile output in Arduino and post a copy of the compile output?

**Comment by GitCode2019** [comment]
It was a Problem with the WEMOS. The solution is to hold the Reset-Button until a connection is established. Then it works.
