### ISSUE TITLE
Installation Wemos D1 mini Pro failed

### ISSUE THREAD

**Issue by Duesendaniel** [jasoncoon/esp8266-fastled-webserver#147]
Installation on D1 mini successful. 
Installation on D1 mini Pro failed. Error while uploading scetch data to SPIFFS.
Where is my mistake.

Arduino: 1.8.9 (Windows 10), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 16M (15M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\Junior\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:23:0:

C:\Users\Junior\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.002

 #    pragma message "FastLED version 3.003.002"

                     ^

In file included from C:\Users\Junior\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\Junior\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:23:

C:\Users\Junior\Documents\Arduino\libraries\FastLED/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

Der Sketch verwendet 357320 Bytes (34%) des Programmspeicherplatzes. Das Maximum sind 1044464 Bytes.
Globale Variablen verwenden 34060 Bytes (41%) des dynamischen Speichers, 47860 Bytes für lokale Variablen verbleiben. Das Maximum sind 81920 Bytes.
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM7
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: 2c:f4:32:65:49:bf
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0240
Compressed 361472 bytes to 255338...

Writing at 0x00000000... (6 %)
Writing at 0x00004000... (12 %)
Writing at 0x00008000... (18 %)
Writing at 0x0000c000... (25 %)
Writing at 0x00010000... (31 %)
Writing at 0x00014000... (37 %)
Writing at 0x00018000... (43 %)
Writing at 0x0001c000... (50 %)
Writing at 0x00020000... (56 %)
Writing at 0x00024000... (62 %)
Writing at 0x00028000... (68 %)
Writing at 0x0002c000... (75 %)
Writing at 0x00030000... (81 %)
Writing at 0x00034000... (87 %)
Writing at 0x00038000... (93 %)
Writing at 0x0003c000... (100 %)
Wrote 361472 bytes (255338 compressed) at 0x00000000 in 22.6 seconds (effective 127.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

[SPIFFS] data    : C:\Users\Junior\Desktop\esp8266-fastled-webserver\data
[SPIFFS] size    : 15340
[SPIFFS] page    : 256
[SPIFFS] block   : 8192
/css/bootstrap.min.css

/css/minicolors.min.css

/css/simple.css

/css/styles.css

/edit.htm

/favicon.ico

/fonts/glyphicons.eot

/fonts/glyphicons.svg

/fonts/glyphicons.ttf

/fonts/glyphicons.woff

/fonts/glyphicons.woff2

/images/atom196.png

/images/github.ico

/index.htm

/js/app.js

/js/bootstrap.min.js

/js/jquery-3.1.1.min.js

/js/minicolors.min.js

/js/r-websocket.min.js

/js/simple.js

/simple.htm

/wifi.htm

[SPIFFS] upload  : C:\Users\Junior\AppData\Local\Temp\arduino_build_829812/esp8266-fastled-webserver.spiffs.bin
[SPIFFS] address  : 0x100000
[SPIFFS] reset    : nodemcu
[SPIFFS] port     : COM7
[SPIFFS] speed    : 115200
[SPIFFS] python   : C:\Users\Junior\AppData\Local\Arduino15\packages\esp8266\tools\python\3.7.2-post1\python.exe
[SPIFFS] uploader : C:\Users\Junior\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\tools\upload.py

esptool.py v2.6

Serial port COM7

Connecting....

Chip is ESP8266EX

Features: WiFi

MAC: 2c:f4:32:65:49:bf

Uploading stub...

Running stub...

Stub running...

Configuring flash size...

Auto-detected Flash size: 4MB

Traceback (most recent call last):

  File "C:\Users\Junior\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\tools\upload.py", line 25, in <module>

    esptool.main(fakeargs)

  File "C:/Users/Junior/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2698, in main

    operation_func(esp, args)

  File "C:/Users/Junior/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2125, in write_flash

    % (argfile.name, argfile.tell(), address, flash_end))

esptool.FatalError: File C:\Users\Junior\AppData\Local\Temp\arduino_build_829812/esp8266-fastled-webserver.spiffs.bin (length 15708160) at offset 1048576 will not fit in 4194304 bytes of flash. Use --flash-size argument, or change flashing address.

SPIFFS Upload failed!

**Comment by jasoncoon** [comment]
The last few lines of your error:

```
esptool.FatalError: File C:\Users\Junior\AppData\Local\Temp\arduino_build_829812/esp8266-fastled-webserver.spiffs.bin (length 15708160) at offset 1048576 will not fit in 4194304 bytes of flash. Use --flash-size argument, or change flashing address.
```

says it's trying to upload 15 MB, which won't fit in the 4MB of flash.  You might check for files that don't belong in the data directory, that seems larger than usual.  Mine's only 770 KB.

You might also try compressing the data directory first, before uploading to SPIFFS.  https://github.com/jasoncoon/esp8266-fastled-webserver#compression

**Comment by Duesendaniel** [comment]
Thank you for your answer.

It is a mystery, my data folder has a size of 664 kB.

I've changed the board settings from WEMOS D1 mini Pro with 16M (15M SPIFFS) to WEMOS D1 R1 & mini with 4M (3M SPIFFS). 
Now it's working.
