### ISSUE TITLE
how to sent command from Domoticz?

### ISSUE THREAD

**Issue by George-Verboven** [jasoncoon/esp8266-fastled-webserver#149]
First of all, great script.
It's all working fine, But I want to use my home domotics system for changing effects.
So it would be great if I could use commands like:
http://192.168.178.53/setPattern(8)
But this is not working, I get": "Not found: /setPattern(8)

Is there a way to solve this problem?

_Using: Domoticz V4.10717 - Wemos D1 mini - WS2812b_

**Comment by jasoncoon** [comment]
Thanks!

This sketch uses a HTTP REST API, which means you can retrieve a value with an HTTP GET:

`GET http://192.168.178.55/pattern`

You set a value with a HTTP POST:

`POST http://$ip/pattern?value=8`

Here's how you can do it in a command line terminal using the curl command:

`curl -X POST http://$ip/pattern?value=8`

**Comment by George-Verboven** [comment]
Thanks Jasoncoon for your reply.
I read also the post: [](https://github.com/jasoncoon/esp8266-fastled-webserver/issues/60)
And when i open the browser developer tools, i'm able to see all the HTTP requests the web app uses.

Using it as command line in windows works great.

But I don't know where to put in domoticz:
`curl -X POST http://192.168.178.53/pattern?value=8`
_(I typed 192.168.178.55,  but it should be 192.168.178.5**3**)_

At least not in the url from the browser ;-).... that would make it easy for using in Domoticz.

**Comment by George-Verboven** [comment]
Command line in windows does work.
![5](https://user-images.githubusercontent.com/53129423/68077010-aa0a6e00-fdbc-11e9-9d0b-63460c6c0c50.JPG)

However in raspberrypi i get:
![4](https://user-images.githubusercontent.com/53129423/68077013-b68ec680-fdbc-11e9-839c-c4d8767d46c5.JPG)

**Comment by George-Verboven** [comment]
**Hi,**

I Changed the Title of this issue to: **How do you set a pattern in Domoticz?**
_Because I wanted to achieve that._
For those who are interested, An explanation how I managed it (thanks to the tips of jasoncoon):

Go to Scripts folder located in domoticz and create new folder in my example "Wemos"
Create new file and add the curl -X POST use the fixed IP address from the WEMOS D1 mini:
![1a](https://user-images.githubusercontent.com/53129423/68088095-de813700-fe5b-11e9-82b2-479c966a182a.JPG)

_Save as, and use the appropriate name._

Test it with LXTerminal:
![1b](https://user-images.githubusercontent.com/53129423/68087335-25b7f980-fe55-11e9-82c6-64f5dbab10a9.JPG)

In Domoticz create new Dummy hardware (Setup -> Hardware)
![1c](https://user-images.githubusercontent.com/53129423/68087429-f655bc80-fe55-11e9-86d0-d7ec3b22409c.JPG)

Create Virtual Sensor. (Use Sensor Type: Selector Switch)
![1d](https://user-images.githubusercontent.com/53129423/68087470-8136b700-fe56-11e9-821a-d69cf97eff87.JPG)

Go to tab Switches and edit the virtual switch:
![1e](https://user-images.githubusercontent.com/53129423/68087542-526d1080-fe57-11e9-993b-fe8e43e8baf6.JPG)

Create Level name (Selector Levels):
![1f](https://user-images.githubusercontent.com/53129423/68087621-fb1b7000-fe57-11e9-812c-9b57b01d1530.JPG)

and Level Action. (Don't forget to save (button bottom left):
![1g](https://user-images.githubusercontent.com/53129423/68087755-cf4cba00-fe58-11e9-98d1-b305e8052bbf.JPG)

Go back to switches and you will see a pull down menu within your virtual Switch with all your effects.
![1h](https://user-images.githubusercontent.com/53129423/68087809-45e9b780-fe59-11e9-8758-7df68c8525b3.JPG)

_Using: Raspberry pi 3b+, Domoticz V4.10717 - Aeotec Gen 5 Z-Wave - Lot's of Z-wave Sensor/Switches - Wemos D1 mini - WS2812b_
