### ISSUE TITLE
DMA driver for ESP8266

### ISSUE THREAD

**Issue by seanspotatobusiness** [jasoncoon/esp8266-fastled-webserver#15]
Hey, I barely know what this is, much less how it could or couldn't fit in with the fastled-webserver but there's a project at the following URL to enable a DMA thing which would increase the capacity of the ESP8266 to control more LEDs: https://github.com/cnlohr/esp8266ws2812i2s

I thought it might be useful but maybe it's not at all.

**Comment by jasoncoon** [comment]
Thanks for sharing!  I'll leave the LED driving specifics to the gurus behind the FastLED library.  :)
