### ISSUE TITLE
Connecting to 5V -> no connection to wifi

### ISSUE THREAD

**Issue by d1nd141** [jasoncoon/esp8266-fastled-webserver#150]
Hi,

I suppose this is not software related, but maybe you could help?
i connected my ws2812 and Wemos D1 to a 5V labo power supply as shown in this image:

http://philipp.stiller.cc/user/pages/02.blog/wemos-d1-mini-ws2812b/Wiring_without_LLC.jpg

The LED's are working(single small light up), the Wemos Blue LED blinks 1*, but does not connect to the wifi. Unfortunately i have no serial log, as not connected to USB.

When i disconnect the 2 cables to Groundand 5V, and connect my USB (Wemos powered via PC, LED via power supply), everything works fine. I can control the LEDS in UI.

Any idea what i did wrong?
Thanks.

**Comment by jasoncoon** [comment]
Can you measure the voltage output from your power supply?

Without serial output, it's hard to guess what's going wrong.  Why not connect the power supply to just the LEDs, and USB to the Wemos?  Disconnect the 5V connection between the LEDs/power supply and the Wemos.  Just connect the grounds together.

**Comment by jasoncoon** [comment]
I'm closing this issue, but feel free to reopen it if needed.
