### ISSUE TITLE
Save default

### ISSUE THREAD

**Issue by jakesza** [jasoncoon/esp8266-fastled-webserver#152]
Is there a way to save a custom pattern that will always default to once powered or rebooted?

**Comment by jasoncoon** [comment]
It currently saves what pattern you have selected, and should start on it after rebooted.  If you don't want that, you'd need to comment out line 775: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L775

Then just set it to whatever pattern index you want on line 112: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L112

**Comment by jasoncoon** [comment]
Closing this issue, feel free to reopen it if needed.
