### ISSUE TITLE
white (255,255,255) looks pinkish

### ISSUE THREAD

**Issue by ghost** [jasoncoon/esp8266-fastled-webserver#153]
i just installed the software on my esp8266 and everything works fine except for the colour white. it has kind of a red tint to it and i’m not sure how to fix it. i never changed anything in the software other than wifi ssid/password.

**Comment by CorpusCallosum** [comment]
This either has something to do with the LEDs you are using, or it could be that you are not supplying them enough power. LEDs will almost never look exactly white, so that will need to be calibrated. If they are not getting enough volts or amps, they will shift towards red, making them look pinkish.

**Comment by bentheball1** [comment]
> This either has something to do with the LEDs you are using, or it could be that you are not supplying them enough power. LEDs will almost never look exactly white, so that will need to be calibrated. If they are not getting enough volts or amps, they will shift towards red, making them look pinkish.

i dont think it would be that because i was just using the tree v2 program and it was fine but maybe i’ll just switch out the cables

**Comment by jasoncoon** [comment]
If you're sure it's not power-related, check the color correction setting.

This sketch uses TypicalLEDStrip: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L228

Tree v2 uses Typical8mmPixel: https://github.com/evilgeniuslabs/tree-v2/blob/master/tree-v2.ino#L247

**Comment by jasoncoon** [comment]
Closing this issue, feel free to reopen it if needed.
