### ISSUE TITLE
Hostname support?

### ISSUE THREAD

**Issue by CorpusCallosum** [jasoncoon/esp8266-fastled-webserver#154]
Hi, I believe an earlier version of this project had support for using a hostname, but that's been taken out. Is there a way to get that working again?

I tried setting the hostname using WiFi.hostname("myname");

But, was unable to connect to the device via the hostname (http://myname.local)

Thanks for your help.

**Comment by jasoncoon** [comment]
Yeah, I commented out a bunch of functionality while trying to track down performance issues, and never bothered re-enabling them.  You'll just need to add mDNS: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino

**Comment by jasoncoon** [comment]
I also realized that hostname wasn't being set in non-ap mode, fixed now: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/main/esp8266-fastled-webserver.ino#L303

Closing this issue, feel free to reopen it if needed.
