### ISSUE TITLE
Matrix with 7x5 Pixel

### ISSUE THREAD

**Issue by Tecky10** [jasoncoon/esp8266-fastled-webserver#156]
Hello, can someone help me to put the project on a matrix with 7x5 pixels? The background is that we are building a lighting system with fairground LEDs and the arrangement is in 5LEDs x 7 strips. Thanks in advance.

**Comment by jasoncoon** [comment]
Have you tried to incorporate FastLED's XYMatrix example? https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino

**Comment by Tecky10** [comment]
That's where I have my problem, I don't know at which point I have to implement the XY matrix example.

**Comment by jasoncoon** [comment]
OK, I threw together a basic XY matrix example branch: https://github.com/jasoncoon/esp8266-fastled-webserver/tree/xy-matrix

**Comment by Tecky10** [comment]
Thanks alot! I'm getting a lot further with that. Thanks for your help. Now I'm going to take a look to adjust the effects for me ... THANKS.

**Comment by Tecky10** [comment]
Hello jasoncoon, I need your help again! Is it possible that the WebApp only works with an active internet connection? Every time I choose a network without internet access, I cannot open the WebApp. Do you have a solution for this?

**Comment by jordanadania** [comment]
You don't have a higher chance of getting help by opening this thread. Please close it?

**Comment by jasoncoon** [comment]
There are commented changes in index.htm you'll need to make to self-host in ap mode.

**Comment by Tecky10** [comment]
Thank you for your help ... i found the code in the index.htm change it and than it works.
