### ISSUE TITLE
Problem displaying the web app on any Webbrowser (Android phone ...)

### ISSUE THREAD

**Issue by Tecky10** [jasoncoon/esp8266-fastled-webserver#157]
Hello, I have a problem with the display of the web app on an Android phone ... the homepage of the web app is not loaded no matter whether I use Chroom or Firefox. The simple side works. Maybe someone has an idea?

![image](https://user-images.githubusercontent.com/58402706/72559082-4fa18980-38a4-11ea-9aa9-96911e170ef5.png)

**Comment by Tecky10** [comment]
can nobody help me?

**Comment by jordanadania** [comment]
That looks like what happens when the board doesn't have enough power.

**Comment by Tecky10** [comment]
Thanks for the hint, but unfortunately that wasn't the problem. Anyone else an idea?

**Comment by Tecky10** [comment]
today i solved the problem. But I don't know how .... I just made the project again and everything works fine after that ...

**Comment by Tecky10** [comment]
Hello, now I'm facing an absolute puzzle. On Wednesday the web interface of my controller was still working normally and today ... as in the picture above, whether on the laptop or cell phone, whether Android or Apple ...

**Comment by Tecky10** [comment]
Is it possible, that I need an active internet connection?

**Comment by jordanadania** [comment]
The only time I needed an active internet connection was when implementing a dark mode theme to the page.

**Comment by ArtursGailis1995** [comment]
Connect your device with browser on your computer. Then open Google Chrome and launch Developer console by pressing F12 key on keyboard. Then go to Console tab and show what error you have. There will be errors if some files are not available or are missing, throws server errors and so.

**Comment by Tecky10** [comment]
I have managed the problem. I have change the following Code in the index.html

`  
  
  

  
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/minicolors.min.css">

  <link rel="stylesheet" href="css/styles.css">
`
