### ISSUE TITLE
Two LED strips over two different pins with the same program

### ISSUE THREAD

**Issue by Tecky10** [jasoncoon/esp8266-fastled-webserver#159]
Can I use the "Parallel" version for my topic mentioned above? Is the "Parallel" branch up to date?

**Comment by parentevan** [comment]
I’m very wet behind the ears, but my understanding is that it is easiest to work with a single strand and separate the code 0-19, and 20-39 (for example)

**Comment by Tecky10** [comment]
Thank you for your post... but i solved my Problem... I used the Parallel Branch and it works perfekt. Thank You

**Comment by Tecky10** [comment]
Ok, now I have a problem and my two LED strips have a different number of lamps. Do you have a solution for me? THANK YOU

**Comment by Tecky10** [comment]
I have managed it i have change the number of the LED in the Line:

`  FastLED.addLeds<LED_TYPE, D4, COLOR_ORDER>(leds,  0 * 60, 60).setCorrection(TypicalLEDStrip);
  FastLED.addLeds<LED_TYPE, D2, COLOR_ORDER>(leds,  1 * 56, 56).setCorrection(TypicalLEDStrip);`

after that all LEDs are working...
