### ISSUE TITLE
esp8266-fastled-webserver vs esp8266-fastled-webserver-master Arduino IDE doesn't like it?

### ISSUE THREAD

**Issue by seanspotatobusiness** [jasoncoon/esp8266-fastled-webserver#16]
While following the instructions in the README (the SPIFFS part, where you open the Arduino sketch in the ID) I get the following dialogue:

[http://imgur.com/oBHhyjI.png](http://imgur.com/oBHhyjI.png)

Clicking yes will separate the ino file from the h files which I guess is wrong? I think changing esp8266-fastled-webserver.ino to esp8266-fastled-webserver-master.ino would solve this.

**Comment by jasoncoon** [comment]
Yeah, you'll need to rename the directory from esp8266-fastled-webserver-master to esp8266-fastled-webserver.
