### ISSUE TITLE
Speed refresh

### ISSUE THREAD

**Issue by dherkes** [jasoncoon/esp8266-fastled-webserver#160]
A compliment first.  Let me thank you for the marvelous software.  I have rarely had more fun using a MCU.  If I can make just one observation.  While a pattern, any pattern, is running and I increase or decrease the speed, the change does not take place until I cycle the power from the soft switch.

**Comment by jordanadania** [comment]
What?

**Comment by jasoncoon** [comment]
That's odd, I don't think I've noticed that.

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
