### ISSUE TITLE
keyboard shortcuts AND new button

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#161]
Not an issue, obviously. I just don't know how else to contact you and I don't know what I am even dealing with enough to know what to google to figure it out for myself.

With that said, how can I program it so I can add some keyboard shortcuts? For instance, hitting 'p' could load a specific pattern. Or + on NumPad could increase brightness by an interval, probably not 1.

You can be as specific or general as you have time for. I will try and fill in the rest, as I have some extra time right now.

I also have the desire to add a new button like a reload button on a browser. Just the simple arrow in a circle. I want it to go to 'Last Pattern'.

I feel like the new button would be easier than the keyboard shortcuts, but that's really just conjecture.

I also made an audio pattern I would be honored for you to check out sometime.

Thanks so much,
Jordan Adania

**Comment by jasoncoon** [comment]
That's a good question, I don't think I've ever implemented keyboard shortcuts in a web app...  I won't have time to look into this for quite some time, but I'd try searching online for "javascript jquery keyboard shortcuts" maybe?  Looking forward to seeing what you come up with!
