### ISSUE TITLE
'D7' was not declared in this scope

### ISSUE THREAD

**Issue by Agentkempo** [jasoncoon/esp8266-fastled-webserver#163]
? I have no clue why it wont work! D7 is the pin I wish to use.

**Comment by Agentkempo** [comment]
Arduino: 1.8.10 (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\s\AppData\Local\Temp\arduino_modified_sketch_783157\esp8266-fastled-webserver.ino:23:0:

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.002

 #    pragma message "FastLED version 3.003.002"

                     ^

In file included from C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/FastLED.h:65:0,

                 from C:\Users\s\AppData\Local\Temp\arduino_modified_sketch_783157\esp8266-fastled-webserver.ino:23:

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/fastspi.h:130:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\s\AppData\Local\Temp\arduino_modified_sketch_783157\esp8266-fastled-webserver.ino:47:0:

C:\Users\s\Documents\Arduino\libraries\rats/Commands.h: In function 'long unsigned int decodeIRCode()':

C:\Users\s\Documents\Arduino\libraries\rats/Commands.h:179:3: error: 'decode_results' was not declared in this scope

   decode_results results;

   ^

C:\Users\s\Documents\Arduino\libraries\rats/Commands.h:179:18: error: expected ';' before 'results'

   decode_results results;

                  ^

C:\Users\s\Documents\Arduino\libraries\rats/Commands.h:181:3: error: 'results' was not declared in this scope

   results.value = 0;

   ^

C:\Users\s\Documents\Arduino\libraries\rats/Commands.h:184:7: error: 'irReceiver' was not declared in this scope

   if (irReceiver.decode(&results)) {

       ^

In file included from C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/FastLED.h:48:0,

                 from C:\Users\s\AppData\Local\Temp\arduino_modified_sketch_783157\esp8266-fastled-webserver.ino:23:

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/fastpin.h: In instantiation of 'class FastPin<16u>':


C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/chipsets.h:574:7:   required from 'class WS2811Controller800Khz<16u, (EOrder)10u>'

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/FastLED.h:111:52:   required from 'class WS2811<16u, (EOrder)10u>'

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/FastLED.h:302:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2811; unsigned char DATA_PIN = 16u; EOrder RGB_ORDER = (EOrder)10u]'

C:\Users\s\AppData\Local\Temp\arduino_modified_sketch_783157\esp8266-fastled-webserver.ino:225:66:   required from here

C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2/fastpin.h:207:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^

Multiple libraries were found for "ESP8266HTTPUpdateServer.h"
 Used: C:\Users\s\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266HTTPUpdateServer
Multiple libraries were found for "WebSocketsServer.h"
 Used: C:\Users\s\Documents\Arduino\libraries\arduinoWebSockets-2.1.4
Multiple libraries were found for "EEPROM.h"
 Used: C:\Users\s\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\EEPROM
Multiple libraries were found for "GradientPalettes.h"
 Used: C:\Users\s\Documents\Arduino\libraries\rats
Multiple libraries were found for "Hash.h"
 Used: C:\Users\s\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\Hash
Multiple libraries were found for "FastLED.h"
 Used: C:\Users\s\Documents\Arduino\libraries\FastLED-3.3.2
Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\s\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi
Multiple libraries were found for "ESP8266WebServer.h"
 Used: C:\Users\s\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer
exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jasoncoon** [comment]
The output says `NodeMCU 0.9 (ESP-12 Module)`, but which specific board are you using?  Tried just `7` instead of `D7`?

**Comment by jordanadania** [comment]
for my nodemcu i had to change things like D5 to 5 and 0 to A0 and 3 and 4 to D3 and D4 depending on... 

`#define DATA_PIN       6`

```
#define MSGEQ7_AUDIO_PIN A0
#define MSGEQ7_RESET_PIN D3
#define MSGEQ7_STROBE_PIN D4
```

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
