### ISSUE TITLE
Would it be possible to add EspAsynceE131 code ?

### ISSUE THREAD

**Issue by 9ghost9** [jasoncoon/esp8266-fastled-webserver#164]
This is more a request/help if possible .

I think your code looks excellent and would be great if one could extend it to cover xmas light hobbyist usage .It would be great to use your code year round and use e131 for  sequenced xmas lights via the multicast .
All advice and suggestions as to how to incorporate this without breaking would be greatly appreciated .

Here is code I would like to add .

``#include <ESP8266WiFi.h>
#include <ESPAsyncE131.h>
#include <FastLED.h>

#define UNIVERSE 1                      // First DMX Universe to listen for
#define UNIVERSE_COUNT 2
#define CHANNEL_START 1
#define DATA_PIN 2
#define NUM_LEDS 170

CRGB newLeds[NUM_LEDS];

const char ssid[] = "SSID";         // Replace with your SSID
const char passphrase[] = "PASSWORD";   // Replace with your WPA2 passphrase

// ESPAsyncE131 instance with UNIVERSE_COUNT buffer slots
ESPAsyncE131 e131(UNIVERSE_COUNT);

void setup() {
  Serial.begin(115200);
  delay(10);

  FastLED.addLeds<WS2812B, DATA_PIN, GRB>(newLeds, NUM_LEDS);

  // Make sure you're in station mode
  WiFi.mode(WIFI_STA);

  Serial.println("");
  Serial.print(F("Connecting to "));
  Serial.print(ssid);

  if (passphrase != NULL)
    WiFi.begin(ssid, passphrase);
  else
    WiFi.begin(ssid);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.print(F("Connected with IP: "));
  Serial.println(WiFi.localIP());

  // Choose one to begin listening for E1.31 data
  //if (e131.begin(E131_UNICAST))                               // Listen via Unicast
  if (e131.begin(E131_MULTICAST, UNIVERSE, UNIVERSE_COUNT))   // Listen via Multicast
    Serial.println(F("Listening for data..."));
  else
    Serial.println(F("*** e131.begin failed ***"));

}
void loop() {
  if (!e131.isEmpty()) {
    e131_packet_t packet;
    e131.pull(&packet);     // Pull packet from ring buffer
    uint16_t universe = htons(packet.universe);
    if (universe == 1) {
      if (packet.property_values[(CHANNEL_START - 1)] < NUM_LEDS) {
        for (int n = 0; n < NUM_LEDS; n++) {
          int j = n * 3 + (CHANNEL_START);
          newLeds[n] = (n, (CRGB(packet.property_values[j] , packet.property_values[j + 1], packet.property_values[j + 2])));
          //Serial.println(packet.property_values[j]);
        }
        FastLED.show();
      }
    }
  }
}
``

**Comment by jasoncoon** [comment]
I haven't used e131 and don't know much about it, but that seems like it should work.

You could likely just add that code inside the existing setup and loop functions, and everything else should continue to work.

Or instead of doing all of that in `loop`, you could rename the function to something else, then just add it to the pattens list.  Then you'd be able to choose other patterns in the web UI, and change to e131 when desired.

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
