### ISSUE TITLE
Red and Green are switched

### ISSUE THREAD

**Issue by FrangosdeMocambique** [jasoncoon/esp8266-fastled-webserver#165]
When I try to choose a single color, on the colors buttons, color wheel and the RGB sliders, the green and the red are switched. For example, when I try to put the red color in any of the options that I said before, always shows me the green and when I move by the reddish tones, on the led strip it is moving by the green tones.

**Comment by ArtursGailis1995** [comment]
Look for 
`#define COLOR_ORDER   GRB`
in esp8266-fastled-webserver.ino and try changing it to
`#define COLOR_ORDER   RGB`

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
