### ISSUE TITLE
Add button on/off

### ISSUE THREAD

**Issue by Qamil991** [jasoncoon/esp8266-fastled-webserver#168]
Hi.
Can you add a button for switching on/off ?

Example
https://www.youtube.com/watch?v=Q9OhOZTY9oI

**Comment by jasoncoon** [comment]
Hello!  Yes!  I did this a while back in the `6xWithSwitches` branch: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/6xWithSwitches/esp8266-fastled-webserver.ino

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
