### ISSUE TITLE
SPIFFS Error: esptool not found!

### ISSUE THREAD

**Issue by fals3illusion** [jasoncoon/esp8266-fastled-webserver#171]
When trying to upload i get an error of 

SPIFFS Error: esptool not found!

So when i tried boards manager esp8266 to version 2.3.0 i get  " SPIFFS Create Failed!" 

I am using a nodemcu esp8266.  Is this possible to use this? or do i have to only use a d1 mini?

**Comment by jasoncoon** [comment]
Have you followed the instructions to install the SPIFFS upload tool?  https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#uploading-files-to-file-system

It should definitely be possible on the NodeMCU ESP8266.

**Comment by sshcrack** [comment]
In the Readme-File is a link to the older tool which works with the .exe file of the ESP tool

**Comment by jasoncoon** [comment]
Closing, reopen if needed.
