### ISSUE TITLE
Not really an issue, I added DMX functionallity to your Webserver.

### ISSUE THREAD

**Issue by TobiasRadtke** [jasoncoon/esp8266-fastled-webserver#172]
For it to work you need to connect the ESP to a circuit like this:
![image](https://user-images.githubusercontent.com/59103500/86360062-24540080-bc72-11ea-9b62-4bd57262ff79.png)
I used a max485 chip.
The Input of the max485 Chip has to be connected to pin D4 of your ESP8266.

Important:
You have to Install the Following library first: https://github.com/Rickgg/ESP-Dmx

You need to change #define NUM_LEDS according to your quantity of DMX Devices.
It only works with DMX lamps that have 4 channels:
(Channel 1:Red/ Channel 2:Green/ Channel 3:Blue/ Channel 4:Dimmer)

I´m relatively new to Arduino so I don´t expect everything to work flawlessly.
If you have any ideas to make it work better please let me know.
Still i wanted to share my achievement with you.

[esp8266-fastled-webserver-DMX.zip](https://github.com/jasoncoon/esp8266-fastled-webserver/files/4864312/esp8266-fastled-webserver-DMX.zip)

**Comment by henrygab** [comment]
Awesome!  Thanks for sharing!
