### ISSUE TITLE
Index Page "Connecting, please wait..." forever

### ISSUE THREAD

**Issue by pacpacaddict** [jasoncoon/esp8266-fastled-webserver#174]
I would like to say I am a big fan of the work and I'm happy to see how active it is. I seem to be running into an issue that is rather uncommon. I am able to compile and upload the sketch, as well as successfully getting SPIFFS to upload the device. I can see it loads, but no controls are given and it constantly says "Connecting, please wait..." I have several errors thrown in the console, and I found the network section is of importance as well, so there are screenshots of both below. I am inexperienced with how JQuery and Bootstrap work, assuming those are where the problem lies, so I've decided to ask for help here.

![Annotation 2020-08-02 175420](https://user-images.githubusercontent.com/28881986/89135325-fae4f980-d4e9-11ea-841b-6ca99f758558.png)

![Annotation 2020-08-02 175420_2](https://user-images.githubusercontent.com/28881986/89135356-3253a600-d4ea-11ea-95b2-f93f17995ace.png)

There you can see the page is blank and the "Connecting, please wait..." at the bottom. At first I believed there may be some error on my part with outdated libraries/boards, but everything has been updated and this still occurs. I have also attempted the mentioned compression method to see if there was a storage limitation on the flash. I'm willing to go digging to get any logs/files that may prove useful, but I would likely need instruction on how to get such logs/files. Any assistance is appreciated!

**Comment by jasoncoon** [comment]
Hey, thank you!  Looks like the websocket connection is failing to connect.  I've disabled websockets for performance reasons, but it looks like the web app is still trying to connect.  The firmware instructs the web browser to cache the js app for quite a long time, so you might need to, with dev tools open, click and hold on the refresh button, then choose `Empty cache and hard reload`.  If that doesn't work, you might try pulling the latest code, compiling and uploading the firmware, and uploading to SPIFFs again.

**Comment by pacpacaddict** [comment]
I appreciate the prompt response! I enjoyed the explanation. It seems I may have had trouble extracting or downloading the zip file. As you suggested, downloading the latest version and recompiling and uploading combined with the Empty cache and hard reset seemed to have fixed everything, and I am greeted with a much more pleasant home page!
