### ISSUE TITLE
Discovered html code failure and want to add thunderstorm 

### ISSUE THREAD

**Issue by catarrer** [jasoncoon/esp8266-fastled-webserver#178]
Hi, i discovered an failer inside the HTML-Code. 

its the index.htm file on line 159. Instead of <select class="form-control"><select> it should be <select class="form-control"></select> (backslash in 2nd tag). :) 

There is an other question i have about the Arduino-code: is there a possibility to add thunderstorm lightnings? I build a Cloud-Lamp which looks awesome but I'm missing lightning like the glitter-effect in Rainbow with Glitter just in solo. Where do i need to add the code? 

yours sincerly
Adrian

**Comment by jasoncoon** [comment]
Fixed, thanks!

You should be able to add a glitter function here: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/main/esp8266-fastled-webserver.ino#L1022

```
void glitter()
{
  addGlitter(80);
}
```

Then just add it to the patterns list somewhere here: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/main/esp8266-fastled-webserver.ino#L170

```
  { glitter,                "Glitter" },
```

**Comment by catarrer** [comment]
awesome! I'll try this. Uploading the Firmware via Fastled-Webserver needs to be compiled first. Am i right?

**Comment by catarrer** [comment]
By adding addglitter(80), the single leds get step by step white and stay white. Today in the evening (GMT+2 local time) i will investigate a bit and respond here my results. 
Thanks for your lightning fast answers.

YS Adrian

**Comment by jasoncoon** [comment]
Ah, right, you'll need to add code to dim them each frame, like:

```
fadeToBlackBy(leds, NUM_LEDS, 10);
```

**Comment by catarrer** [comment]
Absolutely amazing! You guy rocks! Thanks a thousand times... I edited it by changing chance to glitter to 10% and fadeToBlackBy to 5. Now it looks like a huge thunderstorm inside my daughters room. 
Do you have Patreon?

**Comment by jasoncoon** [comment]
Awesome, glad to hear it!  I'd love to see it, if you have a chance to take some video.  You can share it via:

Reddit: https://www.reddit.com/r/FastLED (I'm u/Pup05)
Twitter: https://twitter.com/jasoncoon_
Instagram: https://www.instagram.com/jasoncoon

I don't have a Patreon, but thanks for asking!  I do have a store on Tindie where I sell PCBs, kits, etc: https://www.tindie.com/stores/jasoncoon/items/
If you insist on donating, I do have PayPal: https://www.paypal.com/paypalme/evilgeniuslabs  😆
