### ISSUE TITLE
index page display problem on iPad, iPhone, Safari, M.Edge 

### ISSUE THREAD

**Issue by lumtech** [jasoncoon/esp8266-fastled-webserver#179]
Hi, the Index page on iPad, iPhone (Chrome, Safari) is not loading completely. Also on a desktop Windows computer in the Edge browser and Safari. Only top navbar,  import / export with buttons, bottom navbar with message "Loading, please wait..." are loaded.
How can i fix this?

Other devices and browsers like Android phone, Chrome, FireFox, Opera work fine.

**Comment by henrygab** [comment]
Due to age of this issue, I am closing it.  If you still are experiencing this issue, please re-open or (better for you as it shows up higher on list) open a new issue.
