### ISSUE TITLE
Clock Picker control for web app

### ISSUE THREAD

**Issue by ht81** [jasoncoon/esp8266-fastled-webserver#18]
Hello,

i´m using ESP8266 FastLED Webserver and i would like to implement a clock picker to set on and off time. I have extended the esp8266-fastled-webserver.ino with NTP Time and getting correct time. The big deal is to set the on / off time via the html. I have found this: http://weareoutman.github.io/clockpicker/
is there anybody how can implement this into the located index.html / scripts.js and esp8266-fastled-webserver.ino? Im not able to do that because I do not know about it. Please help me. I need 4 variables in the esp8266-fastled-webserver.ino (OnTimeMinute, OnTimeHour, OffTimeMinute, OffTimeHour--> all as int)

Hope anybody can help me getting this feature implemented

**Comment by rodders99** [comment]
Have you considered executing the on off command from a remote system better suited to the task ?

Websockets allows easy control from external applications. For example, to turn this on or off is a simple curl command which can be setup with cron or any of the home automation platforms : 

curl --request POST http://<ip address>/power --data "value=0" - To turn off
curl --request POST http://<ip address>/power --data "value=1" - To turn on

**Comment by tech-freak** [comment]
@jasoncoon 
is there any update on this ?
as you have already created fork for ESPixelClock

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
