### ISSUE TITLE
I'm dumb sorry but where is the wifi.h file?

### ISSUE THREAD

**Issue by Sparkofmadness** [jasoncoon/esp8266-fastled-webserver#183]
this is my second project with arduino in general. where is wifi.h file to set my wifi ssid and pass in?

**Comment by jasoncoon** [comment]
I recently switched this project over to use [WiFiManager](https://github.com/tzapu/WiFiManager).  You don't have to enter your ssid and password in the code any more.  It'll start up in AP mode.  Connect to its wifi network, and you should get prompted to configure it to connect to your wifi.  Sorry, I haven't updated the readme yet.

**Comment by Sparkofmadness** [comment]
thank you very much(sry for late response,didnt check my e-mail till now)
