### ISSUE TITLE
Wifi Manager has no member names process

### ISSUE THREAD

**Issue by CFalciani** [jasoncoon/esp8266-fastled-webserver#185]
When uploading the esp8266-fastled=webserver.ino file to the esp8266, I am getting the following error:
/home/clayx11/Arduino/esp8266-fastled-webserver/esp8266-fastled-webserver.ino: In function 'void loop()':
esp8266-fastled-webserver:488:15: error: 'class WiFiManager' has no member named 'process'
   wifiManager.process();

Is this an issue with my Wifi Manager install?

**Comment by jasoncoon** [comment]
Likely, you need to be running the development branch version: https://github.com/tzapu/WiFiManager/tree/development

Mentioned here: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/main/esp8266-fastled-webserver.ino#L39

**Comment by CFalciani** [comment]
Yep that seems to resolve the issue. Thanks for the quick reply!
