### ISSUE TITLE
Integrating time clock for automation

### ISSUE THREAD

**Issue by JCastillo059** [jasoncoon/esp8266-fastled-webserver#186]
Hello,

How would I go about integrating time clock into the website so I would be able to automate on/off? Would I add into the file system or firmware? 

Time integration: https://github.com/PaulStoffregen/Time
Automation function: https://github.com/asd0999/Home-automation-with-time-scheduler

Thanks

**Comment by jasoncoon** [comment]
Depends on how complicated you want to get with the schedule(s).  If it's just a simple "turn on at 8am, turn off at 8pm", you could add a new field to Fields.h for "on time" and "off time".
