### ISSUE TITLE
Reupload fails

### ISSUE THREAD

**Issue by N4vL** [jasoncoon/esp8266-fastled-webserver#187]
I already uploaded the web app successfully. (web app runs on Wemos D1 mini and the LEDs can be controlled via the browser)
**Now I want to make a simple change in esp8266-fastled-webserver.ino and upload it again:**
I changed the color order from RGB to GRB since my WS2812B stripe lights up RED when I choose GREEN and lights up GREEN when I choose RED (BLUE works fine).
Unfortunately this small change had no effect whenever I upload the web app again. (I saved esp8266-fastled-webserver.ino and ran ESP8266 Sketch Data Upload again without any failures)

What am I doing wrong?

**Comment by ArtursGailis1995** [comment]
If you change the sketch, you need to reupload the sketch and not the web app (web app only needs to be reuploaded for major changes or if you erased it somehow)

If you change something in the web app, you need to force refresh all the files, as they are cached in your browser. For Google Chrome you can press Ctrl + Shift + R to do that. For mobile its a bit trickier.

**Comment by jasoncoon** [comment]
Yeah, to update the firmware after changing the source code in the .ino or .h files, you need to use the `Upload` button in Arduino.  To update the the web app files (.htm, .js, .css, etc), you'd use the `ESP8266 Sketch Data Upload` tool.
