### ISSUE TITLE
Nothing major. Adding new  menu items

### ISSUE THREAD

**Issue by Quantum99k** [jasoncoon/esp8266-fastled-webserver#188]
I have written a light reactive music sketch and was wondering on how i could add it to the drop down menu of the webserver. i'm also trying to ad a 2nd esp8266 to mimic the output of the webserver. Any ideas on how to go about this?

**Comment by jordanadania** [comment]
I can absolutely help you with both of these issues.

Just message me on Discord:
Evo#8025
