### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OliTech** [jasoncoon/esp8266-fastled-webserver#19]
It seems that the code won't work, at least for me.
The code will comile and the sketch data upload also but after the start the Wemos D1 mini will restart itself all the time.
What are the settings of the Arduino IDE, what are the versions of the IDE and the libs.
Thank you

**Comment by jasoncoon** [comment]
Libraries:
* esp8266 boards 2.3.0
* FastLED 3.1.5
* ESP8266WiFi 1.0.0
* ESP8266WebServer 1.0.0
* IRremoteESP8266 1.0.0

Settings:
* Board: "WeMos D1 R2 & mini"
* CPU Frequency: 160 MHz
* Flash Size: 4M (3M SPIFFS)
* Upload Speed: "921600"

**Comment by jasoncoon** [comment]
What do you see in the Serial Monitor?

**Comment by jasoncoon** [comment]
Closing due to lack of response.
