### ISSUE TITLE
WiFiManager Web UI only

### ISSUE THREAD

**Issue by Jannomag** [jasoncoon/esp8266-fastled-webserver#190]
Hi,
I tried to flash the whole sketch on my Wemos D1 again after I used for something different.
While flashing I checked that the flash will be deleted.
Then I uploaded the data.

Now, when I connect to the AP I'm just getting the WifiManager UI where I can setup the wifi connection instead of the FastLED Webserver UI. 
I don't want to setup a wifi network, I just want the Wemos run as access point.

Any suggestions?

Here's the upload output of data:
```
[SPIFFS] data    : C:\Users\+++\---\Documents\Arduino\esp8266-fastled-webserver\data
[SPIFFS] size    : 2024
[SPIFFS] page    : 256
[SPIFFS] block   : 8192
/css/bootstrap.min.css
/css/minicolors.min.css
/css/simple.css
/css/styles.css
/edit.htm
/favicon.ico
/fonts/glyphicons.eot
/fonts/glyphicons.svg
/fonts/glyphicons.ttf
/fonts/glyphicons.woff
/fonts/glyphicons.woff2
/images/atom196.png
/images/github.ico
/index.htm
/js/app.js
/js/bootstrap.min.js
/js/FileSaver.min.js
/js/jquery-3.1.1.min.js
/js/minicolors.min.js
/js/r-websocket.min.js
/js/simple.js
/simple.htm
/wifi.htm
[SPIFFS] upload  : C:\Users\+++\AppData\Local\Temp\arduino_build_422648/esp8266-fastled-webserver.spiffs.bin
[SPIFFS] address  : 0x200000
[SPIFFS] reset    : --before default_reset --after hard_reset
[SPIFFS] port     : COM7
[SPIFFS] speed    : 921600
[SPIFFS] python   : C:\Users\+++\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1\python3.exe
[SPIFFS] uploader : C:\Users\+++\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\tools\upload.py

esptool.py v2.8
Serial port COM7
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 84:f3:eb:cc:56:14
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 2072576 bytes to 323303...
Wrote 2072576 bytes (323303 compressed) at 0x00200000 in 10.6 seconds (effective 1566.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

EDIT:
Pressing "Exit" doesn't work. The page just sais "exiting" and nothing happens.
When I connect to an existing AP (my phone for example) I can access the FastLED UI. 

Is there any way to still use the ESP as access point as it was when I flashed it the last time (around a year ago)?

**Comment by jasoncoon** [comment]
Ah, I recently added the WiFiManager library, as it makes it very easy to get ESP8266 devices on an existing network.  But it apparently doesn't allow configuration of AP mode.

You should be able to comment out the WiFiManager lines, then in setup, around line 285 use this:

`WiFi.softAP(nameString, "apModePassword");`

**Comment by Jannomag** [comment]
Okay, thanks. I'll try it tomorrow (it's making my workbench more beautiful at work though)

-------- Ursprüngliche Nachricht --------Von: Jason Coon <notifications@github.com> Datum: 05.10.20  15:11  (GMT+01:00) An: jasoncoon/esp8266-fastled-webserver <esp8266-fastled-webserver@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [jasoncoon/esp8266-fastled-webserver] WiFiManager Web UI only (#190) 
Ah, I recently added the WiFiManager library, as it makes it very easy to get ESP8266 devices on an existing network.  But it apparently doesn't allow configuration of AP mode.
You should be able to comment out the WiFiManager lines, then in setup, around line 285 use this:
WiFi.softAP(nameString, "apModePassword");

**Comment by Jannomag** [comment]
That worked!
Thanks

Now I have another problem.
The web ui doesn't look as usual. The simple menu isn't visible and the start page doesn't have the color settings at all.
I just dressed the flash and did a reupload of the data directory.

![Screenshot_20201006-071145_Edge](https://user-images.githubusercontent.com/31586674/95161451-80637f00-07a3-11eb-8460-55dd47c41a95.jpg)
![Screenshot_20201006-071151_Edge](https://user-images.githubusercontent.com/31586674/95161453-80fc1580-07a3-11eb-8dfb-c53304b02996.jpg)

**Comment by jasoncoon** [comment]
Sorry for the delayed response, do you see the files being listed from SPIFFS in the serial monitor?  What do you see in Chrome dev tools?

**Comment by onimoschta** [comment]
i recently updated my christmas tree lighting. i have an older fastled webbserver version from 2019 which works great but i have this problem whily trying to reach the webserver with my mobile phone. Does not matter which browser or phone (tried a few). There is no problem on my PC webbrowser. Tried desktopversion on my smartphone but did not help. The difference is, i can use the simple mode but the color palette is somehow below each other so you have to scroll a bit for all colors.

**Comment by clowrey** [comment]
Thanks! This issue helped me get it working on Access Point mode again :) using this in an off grid site with no Wi-Fi network. Maybe adding a compile time selection for WIFI manager or not would be useful.

**Comment by jurassic73** [comment]
I got the AP mode only working as well but I'm stuck with the same screenshot view above.
