### ISSUE TITLE
Get Values from HTTP request

### ISSUE THREAD

**Issue by Guenni75** [jasoncoon/esp8266-fastled-webserver#196]
Hi.
I made shortcuts on my S9 to change color and patterns on my 8266.
This works fine.
I searched a lot but i can not figure out, how to get values with http get from the 8266 (actual brightness for example).
I can make a slider for setting the brighness, but i can not set the actual brightness value for the slider.

And another little problem.
I can set Fire for example: http://192......./pattern?value=29
and the cooling: http://192...../cooling?value=8

How can I set both with one http request?

**Comment by henrygab** [comment]
The values are available as JSON.  `http://192..../all`
In fact, that's what the built-in web page uses to generate all the configuration fields.

As for setting multiple values at one time ... not currently available.

There's a possibility to eventually support setting multiple values at once, if they are sent as JSON.  If that is of interest, please submit a new issue.
