### ISSUE TITLE
Flicker on LEDs

### ISSUE THREAD

**Issue by FranzKropp** [jasoncoon/esp8266-fastled-webserver#200]
Hi,
I have the opotunity to set some LEDs on a strip to a fixed color, different from the rest of the strip. 2 Blue one for example while the rest shows a solid red. On the blue LEDs I have a bad flicker all the time. The red LEDs also hav a flicker, but not so obvius. You has to look twice to see it.

A strange thing is that this flicker not showing up if I attache a 8*8 LED Array. 

Any hind what's wrong??

https://user-images.githubusercontent.com/64696976/107413942-aada9580-6b11-11eb-958d-ba3f1763e70d.MOV

End of the Loop Sektion:

 leds[1] = CRGB (0, 0, 200); 
 leds[4] = CRGB (0, 0, 200); 

  FastLED.show();

  // insert a delay to keep the framerate modest
  FastLED.delay(1000 / FRAMES_PER_SECOND);

**Comment by FranzKropp** [comment]
I figured out that the Problem occours only on an older WS2812 Strip. This Strip works fine for several Years with the Adafruit_NeoPixel Library. 

Adafruit_NeoPixel(LEDMax, PIN, NEO_GRB + NEO_KHZ800)

Now:
#define LED_TYPE      WS2812
#define COLOR_ORDER   GRB
FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, LEDMax);         // for WS2812 (Neopixel)

**Comment by CorpusCallosum** [comment]
Hi @FranzKropp  I'm having the same issue with my strip. How did you fix the problem?

**Comment by FranzKropp** [comment]
Hi, I just used a new Stripe :-(
