### ISSUE TITLE
Script.js can not cached!

### ISSUE THREAD

**Issue by EagleSmith** [jasoncoon/esp8266-fastled-webserver#21]
why the brower can't cache script.js file ,Every time download from esp8266, it's too slow .
can you fix this ?thanks,sorry for my english.

**Comment by jasoncoon** [comment]
You can copy the 'max-age" to the lines serving index.htm and js files from the other lines here: https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L261
