### ISSUE TITLE
New file system

### ISSUE THREAD

**Issue by dherkes** [jasoncoon/esp8266-fastled-webserver#210]
Good evening,

Is there a chance the parallel version of the esp8266-fastled-webserver will incorporate the LittleFS?

Thanks.

**Comment by jasoncoon** [comment]
Yeah, the plan is to consolidate all of the branches, with the differences (pin numbers and counts, pixel maps, etc) being handled via configuration: https://github.com/jasoncoon/esp8266-fastled-webserver/discussions/207

**Comment by henrygab** [comment]
This should be closed by #209.
