### ISSUE TITLE
How to use palettes defined in GradientPalettes.h?

### ISSUE THREAD

**Issue by rlesac** [jasoncoon/esp8266-fastled-webserver#22]
I only see the ones defined in the ino file:
const String paletteNames[paletteCount] = {
  "Rainbow",
  "Rainbow Stripe",
  "Cloud",
  "Lava",
  "Ocean",
  "Forest",
  "Party",
  "Heat",
};

**Comment by jasoncoon** [comment]
You'd need to either define a new array for the gradient palette names, or consolidate them into one array.  It's on my todo list, but I have no idea if/when I'll get around to it.

**Comment by raphaelouzan** [comment]
The ideal would be to add all palettes into one array to benefit from the autoplay/palette change mechanism. However, I could not find a way to add both standard palettes and gradient palettes in the same array. The former are TProgmemRGBPalette16 and the gradient palettes have a different type. They can all be converted to CRGBPalette16 at runtime but didn't find a way to declare them under a similar type/type hierarchy. If you have an idea on how to do that, I'm happy to create a pull request that merges them both.

**Comment by qawsed55** [comment]
I have make next:
add this code to the end of GradientPalettes.h:
`  
CRGBPalette16  Sunset_Real              = Sunset_Real_gp  ;
CRGBPalette16  es_rivendell_15          = es_rivendell_15_gp  ;
CRGBPalette16  es_ocean_breeze_036      = es_ocean_breeze_036_gp  ;
CRGBPalette16  rgi_15                   = rgi_15_gp ;
CRGBPalette16  retro2_16                = retro2_16_gp  ;
CRGBPalette16  Analogous_1              = Analogous_1_gp  ;
CRGBPalette16  es_pinksplash_08         = es_pinksplash_08_gp ;
CRGBPalette16  Coral_reef               = Coral_reef_gp ;
CRGBPalette16  es_ocean_breeze_068      = es_ocean_breeze_068_gp  ;
CRGBPalette16  es_pinksplash_07         = es_pinksplash_07_gp ;
CRGBPalette16  es_vintage_01            = es_vintage_01_gp  ;
CRGBPalette16  departure                = departure_gp  ;
CRGBPalette16  es_landscape_64          = es_landscape_64_gp  ;
CRGBPalette16  es_landscape_33          = es_landscape_33_gp  ;
CRGBPalette16  rainbowsherbet           = rainbowsherbet_gp ;
CRGBPalette16  gr65_hult                = gr65_hult_gp  ;
CRGBPalette16  gr64_hult                = gr64_hult_gp  ;
CRGBPalette16  GMT_drywet               = GMT_drywet_gp ;
CRGBPalette16  ib_jul01                 = ib_jul01_gp ;
CRGBPalette16  es_vintage_57            = es_vintage_57_gp  ;
CRGBPalette16  ib15                     = ib15_gp ;
CRGBPalette16  Fuschia_7                = Fuschia_7_gp  ;
CRGBPalette16  es_emerald_dragon_08     = es_emerald_dragon_08_gp ;
CRGBPalette16  lava                     = lava_gp ;
CRGBPalette16  fire_pal                 = fire_pal_gp ;
CRGBPalette16  Colorfull                = Colorfull_gp  ;
CRGBPalette16  Magenta_Evening          = Magenta_Evening_gp  ;
CRGBPalette16  Pink_Purple              = Pink_Purple_gp  ;
CRGBPalette16  es_autumn_19             = es_autumn_19_gp ;
CRGBPalette16  BlacK_Blue_Magenta_White = BlacK_Blue_Magenta_White_gp ;
CRGBPalette16  BlacK_Magenta_Red        = BlacK_Magenta_Red_gp  ;
CRGBPalette16  BlacK_Red_Magenta_Yellow = BlacK_Red_Magenta_Yellow_gp ;
CRGBPalette16  Blue_Cyan_Yellow         = Blue_Cyan_Yellow_gp ;`

then make structures with palettes like this:
```
typedef struct {
  CRGBPalette16 palette;
  String name;
} PaletteAndName;
typedef PaletteAndName PaletteAndNameList[];

CRGBPalette16 palettes[] = {
  RainbowColors_p,
  RainbowStripeColors_p,
  CloudColors_p,
  LavaColors_p,
  OceanColors_p,
  ForestColors_p,
  PartyColors_p,
  HeatColors_p,
  IceColors_p,
  Sunset_Real, 
  es_rivendell_15, 
  es_ocean_breeze_036, 
  rgi_15, 
  retro2_16, 
  Analogous_1, 
  es_pinksplash_08, 
  Coral_reef, 
  es_ocean_breeze_068, 
  es_pinksplash_07, 
  es_vintage_01, 
  departure, 
  es_landscape_64, 
  es_landscape_33, 
  rainbowsherbet, 
  gr65_hult, 
  gr64_hult, 
  GMT_drywet, 
  ib_jul01, 
  es_vintage_57, 
  ib15, 
  Fuschia_7, 
  es_emerald_dragon_08, 
  lava, 
  fire_pal, 
  Colorfull, 
  Magenta_Evening, 
  Pink_Purple, 
  es_autumn_19, 
  BlacK_Blue_Magenta_White, 
  BlacK_Magenta_Red, 
  BlacK_Red_Magenta_Yellow, 
  Blue_Cyan_Yellow,
};

const uint8_t paletteCount = ARRAY_SIZE(palettes);

String paletteNames[paletteCount] = {
  "RainbowColors",
  "RainbowStripeColors",
  "CloudColors",
  "LavaColors",
  "OceanColors",
  "ForestColors",
  "PartyColors",
  "HeatColors",
  "IceColors",
  "Sunset_Real",
  "es_rivendell_15",
  "es_ocean_breeze_036",
  "rgi_15",
  "retro2_16",
  "Analogous_1",
  "es_pinksplash8",
  "Coral_reef",
  "es_ocean_breeze",
  "es_pinksplash7",
  "es_vintage1",
  "departure",
  "es_landscape64",
  "es_landscape33",
  "rainbowsherbet",
  "gr65_hult",
  "gr64_hult",
  "GMT_drywet",
  "ib_jul01",
  "es_vintage57",
  "ib15",
  "Fuschia_7",
  "es_emerald_dragon",
  "Lava",
  "Fire Palette",
  "Colorfull",
  "Magenta_Evening",
  "Pink_Purple",
  "es_Autumn_19",
  "BlacK_Blue_Magenta_White",
  "BlacK_Magenta_Red",
  "BlacK_Red_Magenta_Yellow",
  "Blue_Cyan_Yellow",
};
```
And now you can use gradientPalettes as usual palettes. Clear main code for vars for gradientpalettes if you dont need it.
In my case - this works OK, but I'm not sure that is "well done code".

**Comment by FreezyExp** [comment]
in #135 I split these into a seperate file, along with a CustomPalettes.h and .c to makes this easier to get into.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
