### ISSUE TITLE
map.cpp - Fix regression for "up" direction, as used by clocks

### ISSUE THREAD

**Issue by henrygab** [jasoncoon/esp8266-fastled-webserver#225]
This is to capture the discussion regarding which way is defaulting to "up" on each board.  Specifically, as part of PR #213, "up" was defined to use `64u - hour` (etc.).  See commit 0702b2664362d354b25e28da9d4d2b874aba383b, file `map.cpp`.

However, IIRC, the original branches used different values for "up" when defining the clock's location for 3/6/9/12.  The issue tracks the review of the following two functions, back to the original (per-product) branches:

* `drawAnalogClock()`
* `drawSpiralAnalogClock()`

The branches in question are:

* [x] `1628-rings` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/e2103eab5ee23044e35d94917e2223957110207b/Map.h#L265-L267) used `255 - hour`
* [x] `kraken64` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/58e7da09c01944cf2d904ea5bbd025ee80558fc9/Map.h#L225-L227) used `255 - hour`
* [x] `parallel` -- N/A, map.h did not exist in that branch
* [x] `fibonacci256` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/7f3ef47d9217ac3dfcd2a309d025987fc0d0ba5a/Map.h#L225-L227) used `64 - hour`
* [x] `fibonacci512mini` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/3e5256b698f01e4fc3f810e6751abc0d52555958/Map.h#L234-L236) used `255 - hour`
* [x] `fibonacci128` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/2539b8b83fe1cad2d4100d63581512f6e5d368c4/Map.h#L226-L228) used `255 - hour`
* [x] `fibonacci64` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/4de32fb82915f9a1e30e9671a3b28e4f84a7c190/Map.h#L197-L199) used `255 - hour`
* [x] `fibonacci32mini` -- [Map.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/d89c2131a687ca029df712dac7a0041d4af3c66e/Map.h#L226-L228) used `255 - hour`

As can be see, every branch calculated "up" as `255 - hour`, with the exception of `Fibonacci256`.  Only `Fibonacci256` calculated it as the currently-checked-in code does (using `64u - hour`).  As an aside, it would likely be more correct to use `256u - hour` ... casting to `uint8_t` to cause angle to remain in range [0..255] ... for the other products.

This leaves only one question:

* [ ] Decide how to fix this, or have regressions in all boards other than Fibonacci256

**Comment by henrygab** [comment]
@jasoncoon -- I can see two simple ways to fix this.

1. rotate the positions / angles of `Fibonacci256`, so that up is at zero degrees (256u ... matching all others)

2. define new symbol `WHICH_WAY_IS_UP` for configuration, used only by Fibonacci256


I'm leaning towards the first option.  It would entail the following:

A. Subtract 64 from the values stored in `angles`
B. Rotate values stored in both `coordsX` and `coordsY` counter-clockwise 90 degrees:
    * `newX[i] := 255 - oldY[i]`
    * `newY[i] := oldX`

Which would you prefer?

**Comment by jasoncoon** [comment]
I've confirmed the current `64 - hour` works for all of the Fibonacci PCBs.

I should enable the clock patterns for 1628 rings, but they probably don't make any sense for kraken and chamaeleon.

**Comment by henrygab** [comment]
Ok, I'm fine either way... just wanted to ensure it was a conscious decision, and not an accidental regression.

Note that this will change behavior for existing boards that upgrade, by effectively rotating the output 90 degrees.  I'll add to the wiki.
