### ISSUE TITLE
Wiring Connections?

### ISSUE THREAD

**Issue by issacsim** [jasoncoon/esp8266-fastled-webserver#23]
Hello,

Is there a wiring diagram anywhere?
Wired like instruction on the Adarfruit site (link below), work fine on Arduino uno, but not on ESP8266

https://learn.adafruit.com/adafruit-neopixel-uberguide/basic-connections

Using this board,
https://www.amazon.com/gp/product/B010O1G1ES/

**Comment by issacsim** [comment]
Here is what I get in the com window;

`Heap: 38808
Boot Vers: 31
CPU: 80
SDK: 1.5.3(aec24ac9)
Chip ID: 1494315
Flash ID: 1458415
Flash Size: 4194304
Vcc: 65535

scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 14
cnt 

connected with ISWiFi, channel 1
dhcp client start...
FS File: /css/styles.css, size: 229396
FS File: /favicon.ico, size: 4286
FS File: /fonts/glyphico.eot, size: 20127
FS File: /fonts/glyphico.svg, size: 108738
FS File: /fonts/glyphico.ttf, size: 45404
FS File: /fonts/glyphico.woff, size: 23424
FS File: /fonts/glyphico.woff2, size: 18028
chg_B1:-40
FS File: /images/atom196.png, size: 5469
FS File: /index.htm, size: 5249
FS File: /js/scripts.js, size: 155046

Connecting to WiFi
.chg_B1:-80
..chg_B1:-120
..ip:192.168.1.205,mask:255.255.255.0,gw:192.168.1.1
.Connected! Open http://192.168.1.205 in your browser
HTTP server started
pm open,type:2 0`

**Comment by issacsim** [comment]
Tried couple of other sketches with my same connection on  the ESP8266, one with Adafruit_NeoPixel works fine.
On the FastLED library I am getting No hardware SPI pins defined.

Thank for any help!

**Comment by jasoncoon** [comment]
The sketch defaults to D8, but you can change it to whatever pin you're using.  I've only tested with the Adafruit HUZZAH ESP8266 and Wemos D1 Mini.

The "no hardware SPI pins defined" warning is fine, FastLED doesn't support hardware SPI on the ESP8266 yet.

Looks like it's starting up fine, does the web UI work?  I assume you've tried toggling the on/off buttons, changed the brightness, etc?

Tried any simpler FastLED examples yet?

Good luck, hope you get it working!

**Comment by issacsim** [comment]
Thanks  Jason,

I did change pin to 4 (works on other sketches) Web UI works and I did try on/off and all other settings on the UI. 

Other FastLED examples did not work either for me.

I am going to try the link below when I get home.

https://github.com/FastLED/FastLED/wiki/ESP8266-notes

Thanks!

**Comment by jasoncoon** [comment]
Yeah, I definitely recommend getting a simpler FastLED example working first.  There are a lot of moving parts in this app.  :)

**Comment by issacsim** [comment]
Jason,
Adding line below did the trick.
#define FASTLED_ESP8266_RAW_PIN_ORDER

Also had to get rid of the resistor on the data line.

One more question, do you have a sample anywhere on how to send post commands? like power off?

**Comment by jasoncoon** [comment]
You can use curl to send POST requests, there's an example here: https://github.com/evilgeniuslabs/tree-v2/blob/master/power.sh

```
curl -X POST http://192.168.1.205/power?value=0
curl -X POST http://192.168.1.205/power?value=1
```

**Comment by issacsim** [comment]
Got it, thanks!
