### ISSUE TITLE
running Pacifica

### ISSUE THREAD

**Issue by Semafoor87** [jasoncoon/esp8266-fastled-webserver#246]
Hi all,
I've been breaking my head over this one:
I've had the pacifica code (stand-alone) running on a WeMos D1 mini before I switched to this code.
Within this fastled webserver project, there is a reference to the Pacifica.ccp file, but when I go to the webserver I don't see any option to actually "play" it.

How do I run Pacifica on the fastled webserver?

best,

**Comment by jasoncoon** [comment]
Hey, pull the latest code, should work now. Just needed to move it up: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/1b8929c86eb7d42233ff48b41c7c7d516ac8213f

**Comment by Semafoor87** [comment]
Wow Jason, thanks so much!
