### ISSUE TITLE
Default Brightness not setting

### ISSUE THREAD

**Issue by piratedevon** [jasoncoon/esp8266-fastled-webserver#25]
On boot up, the ESP will recall past patterns, pallets, on/off status etc. but it always defaults to a low brightness level. What is strange is that the web app shows the right value on boot up but then the LEDs are dim so I don't think its in the EPROM but something else.

Using a wemos D1, have seen this with other ESP chips too.

**Comment by awilhelmer** [comment]
look at my commit on: https://github.com/jasoncoon/esp8266-fastled-webserver/issues/4

**Comment by jasoncoon** [comment]
Ah, sorry I missed that, thanks for catching it.  I'll get it fixed soon.  Thanks!

**Comment by piratedevon** [comment]
So put the brightness init before the fastled init?
