### ISSUE TITLE
Voltage Spikes in Animations

### ISSUE THREAD

**Issue by DonSlaughter** [jasoncoon/esp8266-fastled-webserver#28]
The standard colors work perfectly with an nodeMCU but in the Animation some LED's will blink even when its not their time. It looks like Voltage Peaks but they work with the same circuit with another led programm but there is no webinterface which is really gread. I can only use it to show solid colors.

**Comment by jasoncoon** [comment]
Try adding #define FASTLED_ALLOW_INTERRUPTS 0 to the top of the sketch, before the FastLED include, as suggested here: https://github.com/FastLED/FastLED/issues/306

**Comment by DonSlaughter** [comment]
That was very fast. It worked thank you.
