### ISSUE TITLE
colorwave,.. problems

### ISSUE THREAD

**Issue by hamsafar** [jasoncoon/esp8266-fastled-webserver#3]
Hi
First question: which compiler do you use? why I have to declare functions in arduino IDE?
second question: after I declare functions I still have errors "'colorwaves' was not declared in this scope"
sorry for my English
thanks

**Comment by jasoncoon** [comment]
I'm using Arduino 1.6.8 with ESP8266 board version 2.2.0, compiles fine.  Which versions are you using?  The last few versions of Arduino have had an issue with requiring forward declarations for some functions, depending on the libraries you're including.  Might need to add `void colorwaves();` towards the top of the file.

**Comment by hamsafar** [comment]
Hi
Thanks, my problem solved. I use eclipse for compile and ESP8266-12F.
Thanks
