### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by matthewjporter** [jasoncoon/esp8266-fastled-webserver#30]
Hi,

I am getting the following error when compiling "'decode_results' was not declared in this scope"

It happens on command.h

Any suggestions where to start in the code

Cheers

**Comment by jasoncoon** [comment]
Which branch?  What version of Arduino?  Post the full compile output here or at https://gist.github.com or https://pastebin.com

**Comment by matthewjporter** [comment]
Hi Jason


It is the master branch and running on wemos d1 mini


Only thing I do not have an IR sensor connected


I am currently running a 144 led ws3812 & a 60led apa102 strips (seperate D1 mini's) via the adafruit library with a simple websockets server and wifi access to run the effect with no problem


I have tested my units with the simple fastled strandtest and works on both chipsets with


Regards
Matthew Porter
________________________________

**Comment by rnoxious** [comment]
I'm having the same issue.

**Comment by jasoncoon** [comment]
What version of Arduino? Post the full compile output here or at https://gist.github.com or https://pastebin.com

**Comment by rnoxious** [comment]
I'm in 1.6.9 I pasted the output.

Thanks for the help

**Comment by rnoxious** [comment]
I do not have an IR sensor connected either. If that's going to have an affect but I assume not.

**Comment by jasoncoon** [comment]
Ah, found the issue.  I'm apparently using https://github.com/sebastienwarin/IRremoteESP8266, which is different than the one specified in the instructions here (https://github.com/markszabo/IRremoteESP8266).  Sorry, I don't have time right now to update to the new version or update the instructions.  You can try switching, it should work then.  Sorry for the trouble.

**Comment by rnoxious** [comment]
I've tried this several times and the best I can get is jibberish from the serial  monitor.

https://gist.github.com/rnoxious/4ffbee758528860f8e8bcbb0213846b6

**Comment by rnoxious** [comment]
I was missing the upload tool.

https://github.com/esp8266/arduino-esp8266fs-plugin/releases/tag/0.2.0

**Comment by rnoxious** [comment]
This is a great collection of code. Thank you!

**Comment by matthewjporter** [comment]
Hi Jason

I have changed the IR Library but get the same error when compiling

I have now also had to comment out IRrecv irReceiver(RECV_PIN); in the .ino

Moving onto another project, cheers

**Comment by matthewjporter** [comment]
Finally resolved this by following the correct library upload instruction here: https://github.com/sebastienwarin/IRremoteESP8266
