### ISSUE TITLE
functions not bound to selected palette

### ISSUE THREAD

**Issue by rnoxious** [jasoncoon/esp8266-fastled-webserver#31]
The functions confetti,sinelon,bpm,juggle and colorwaves appear to be written to take into account the current color palette chosen. They all seem to follow that rule except for colorwave. Colorwave appears to just cycle and not be bound to the current selected palette.

**Comment by jasoncoon** [comment]
Yep, colorwaves uses a different set of gradient palettes.  I've been debating on ways to consolidate down to one palette list, just haven't gotten around to it.

**Comment by rnoxious** [comment]
That would explain it. Sorry I'm having a tough start wrapping my head around fastled and esp8266. I've done php in the past and that gives me the confidence to be dangerous.

**Comment by jasoncoon** [comment]
No problem!  It definitely can take a while to learn it.  Started with basic Arduino & C/C++ tutorials?  Worked through the FastLED examples?  You might check out these tutorials, if you haven't already:

https://www.slideshare.net/atuline/fast-introduction-to-arduino-and-addressable-led-strips
http://jwhendy.blogspot.com/2015/10/fastled-series-getting-started.html
http://jwhendy.blogspot.com/2015/10/fastled-series-back-and-forth.html

**Comment by rnoxious** [comment]
I'll check them out.

I've got your current code running a set of lights around my pool.
