### ISSUE TITLE
cant compile the sketch

### ISSUE THREAD

**Issue by ErfanDL** [jasoncoon/esp8266-fastled-webserver#32]
Hi thanks for this project. But I cant compile and getting error. 

```
Arduino: 1.8.3 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from C:\Users\STRIX\Desktop\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:0:

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.005

 #    pragma message "FastLED version 3.001.005"

                     ^

In file included from C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/FastLED.h:65:0,

                 from C:\Users\STRIX\Desktop\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/FastLED.h:48:0,

                 from C:\Users\STRIX\Desktop\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/fastpin.h: In instantiation of 'class FastPin<15u>':

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<15, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/chipsets.h:468:7:   required from 'class WS2812Controller800Khz<15u, (EOrder)66u>'

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/FastLED.h:100:52:   required from 'class WS2812<15u, (EOrder)66u>'

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/FastLED.h:294:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812; unsigned char DATA_PIN = 15u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\STRIX\Desktop\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:105:66:   required from here

C:\Users\STRIX\Documents\Arduino\libraries\FastLED-master/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by jasoncoon** [comment]
What pin are you using?  You'll need to use a NodeMCU defined pin.

**Comment by b0tting** [comment]
To extend on Jason's remark, look up "FASTLED_ESP8266_RAW_PIN_ORDER"

**Comment by jemd15** [comment]
i think i have the same mistake... I'm not sure what is the invalid pin. 
<pre>
In file included from C:\Users\x_jem\OneDrive\Documentos\proyectos\arduino\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:0:

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006

 #    pragma message "FastLED version 3.001.006"

                     ^

In file included from C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/FastLED.h:68:0,

                 from C:\Users\x_jem\OneDrive\Documentos\proyectos\arduino\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/FastLED.h:51:0,

                 from C:\Users\x_jem\OneDrive\Documentos\proyectos\arduino\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/fastpin.h: In instantiation of 'class FastPin<15u>':

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<15, 20, 50, 30, (EOrder)66u, 0, false, 5>'

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/chipsets.h:468:7:   required from 'class WS2812Controller800Khz<15u, (EOrder)66u>'

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/FastLED.h:105:52:   required from 'class WS2812B<15u, (EOrder)66u>'

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/FastLED.h:297:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 15u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\x_jem\OneDrive\Documentos\proyectos\arduino\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:105:66:   required from here

C:\Users\x_jem\OneDrive\Documentos\Arduino\libraries\FastLED-master/fastpin.h:206:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");
</pre>

**Comment by jasoncoon** [comment]
Yeah, looks like the same problem, and it should have the same solution.  Have you tried defining FASTLED_ESP8266_RAW_PIN_ORDER?

**Comment by jemd15** [comment]
no, sorry... I don't know how to do that :(

**Comment by jasoncoon** [comment]
https://github.com/FastLED/FastLED/wiki/ESP8266-notes

**Comment by jemd15** [comment]
I put the code like this
<pre>
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#include "FastLED.h"
FASTLED_USING_NAMESPACE

extern "C" {
#include "user_interface.h"
}

#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <FS.h>
#include <EEPROM.h>
#include <IRremoteESP8266.h>
#include "GradientPalettes.h"

#define RECV_PIN 12
IRrecv irReceiver(RECV_PIN);
.
.
.
</pre>

but still not working :(

**Comment by jemd15** [comment]
[https://gist.github.com/jemd15/c10b115c2dd3f9e84c965f15f34d790f](url)

basically I took your code and added before the #include "FastLED.h" statement
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER and modify the quantity of leds of 24 to 12

**Comment by jasoncoon** [comment]
Try:

#define DATA_PIN      8

Intead of:

#define DATA_PIN      D8

**Comment by jemd15** [comment]
Man, I love you. I'm an idiot. Thanks fot the help :)

**Comment by jasoncoon** [comment]
Not at all, no worries!  :)
