### ISSUE TITLE
Sketch data upload tool

### ISSUE THREAD

**Issue by jgueydan** [jasoncoon/esp8266-fastled-webserver#34]
Having some issues using the ESP8266 Sketch data upload tool.  I get the following errors:

https://gist.github.com/anonymous/5ec81fb075af5812840babe6ac55a7e1

I'm using the Huzzah 8266 board, Arduino IDE 1.65, latest FASTLED master library.  I have the web files saved in my sketch folder, under /esp8266-fastled-webserver/data

**Comment by jasoncoon** [comment]
Sorry, not sure, but a quick search found this, which seems related: https://github.com/esp8266/arduino-esp8266fs-plugin/issues/22

You might try a newer version of Arduino.
