### ISSUE TITLE
Not Working with NodeMCU

### ISSUE THREAD

**Issue by DonSlaughter** [jasoncoon/esp8266-fastled-webserver#38]
Somehow everything worked before, but not after using the my NodeMCU for another Project I cant get your Code working.

Line 18 - 21
#define FASTLED_ALLOW_INTERRUPTS 0
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#include "FastLED.h"
FASTLED_USING_NAMESPACE

The Pixel have enough Current and Voltage. An they are connectet to Pin D8.

**Comment by DonSlaughter** [comment]
Sorry I forgot to include that i had to commet out
"static_assert(validpin(), "Invalid pin specified");"
in the FastLED library. Else it woulden't compile at all.

**Comment by jasoncoon** [comment]
Tried any of the suggested solutions in these issues?

https://github.com/jasoncoon/esp8266-fastled-webserver/issues?utf8=%E2%9C%93&q=is%3Aissue%20nodemcu

In particular, this one should help:

https://github.com/jasoncoon/esp8266-fastled-webserver/issues/32

**Comment by jasoncoon** [comment]
Or here:

https://github.com/FastLED/FastLED/wiki/ESP8266-notes

**Comment by DonSlaughter** [comment]
Changing D8 to 8 worked. maybe you could add that to your readme. 

or include it in the .ino file

#define FASTLED_ALLOW_INTERRUPTS 0
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
and D8 to 8

for the NodeMCU

**Comment by DonSlaughter** [comment]
Thanks changing D8 to 8 worked for me.

Maybe you could add that to your .ino file if there are more NodeMCU users.

#define FASTLED_ALLOW_INTERRUPTS 0
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
and D8 to 8

**Comment by jasoncoon** [comment]
Cool, glad it worked for you.

Since it's used by people using lots of different ESP8266 boards, not just NodeMCU, it might be better as a comment.

This is an open source project, I would welcome a pull request with your suggested changes.  :)

Thanks!
