### ISSUE TITLE
Reset loops when LEDs greater than ~200

### ISSUE THREAD

**Issue by coopooc** [jasoncoon/esp8266-fastled-webserver#39]
Been troubleshooting this for days and I've finally sorted it out. If I have the number of LEDs any higher than 200 (I don't know the precise number) my NodeMCU ESP-12e just loops on startup. Right when it's trying to get on WiFi it resets. I don't even have the strip wired up at this point. 

Anyone else experience this?

**Comment by jasoncoon** [comment]
I have not experienced that, but I'm using the Wemos D1 Mini Pro.  I haven't used any of the NodeMCU boards.  Have you tried overclocking to 160MHz?  Have you made any changes to the code?  Are you using the master branch (v1.0) or v1.1?

What type of LEDs are you using?  I have one piece with 200 WS2811, one with 255 APA102, and another with 240 WS2812B.

**Comment by coopooc** [comment]
Not sure I'd know how to overclock but I'll do some googling on that and try it. 

I have made minor changes to the code like new patterns but I'm working from a known-working version I've used on another project. Pretty much the only significant change is the size of the strip.

I'm using WS2812B, the weird 12v ones though. The ultimate length will be 470 leds. They aren't wired up right now though. During testing I only used 200 to keep the power draw low, everything worked fine. When I went to 300 it started looping so I disconnected them to help troubleshoot. 

Super weird.

**Comment by coopooc** [comment]
Apparently changing the clock speed is stupid easy. Tried 160, same issue. Dang

**Comment by jasoncoon** [comment]
Once NUM_LEDS >= 256, you'll need to change any variables used as LED index from uint8_t or byte (0-255) to uint16_t (0-65535).  Otherwise, a loop like this will never exit, since `i` will overflow from 255 to 0, and never be greater than or equal to 300.  If the loop never exits, the WDT (watchdog timer) will reset the board.

```
#define NUM_LEDS 300
...
for(uint8_t i = 0; i < NUM_LEDS; i++) {
  leds[i] = CRGB::Red;
}
```

**Comment by coopooc** [comment]
That makes perfect sense. I assume it's not going to be as easy as a find and replace though. If you haven't guessed by now, I still have my training wheels on here. Full "learning from scratch" mode. I'll start trying to make the change and see what happens. Thanks a ton!

**Comment by jasoncoon** [comment]
If you're using the master branch, all of the existing code uses int or uint16_t, and should be safe for up to 65525 LEDs.  Start by checking any new code you've added.

**Comment by coopooc** [comment]
I'm using the 1.1 branch. I forgot you asked that above, probably would have been good to know. Shockingly though, a find and replace was effective after some trial and error. It's running! Patterns look "off" but I suspect that is due to the 160 clock change. Thanks a ton for your help!

**Comment by jasoncoon** [comment]
Great!  Glad you got it working.  :)

**Comment by coopooc** [comment]
I think I spoke too soon. I know this issue is closed but I wonder if you have any theories to explain what's going on. So, everything was up and running perfectly for about 5 minutes with the full strip of 470 LEDs. I was using the web interface to go through the patterns. When I got to water, it did a reset on me. No problem but I realized it was then in a reset loop. It refused to come out of the loop. I uploaded the sketch again, rewrote the SPIFF (or whatever it's called), nothing would pull it out of that reset loop. UNTIL, I lowered the LED count to 300 and then it worked fine again and booted normally. 

What is going on? I just don't know where to start troubleshooting. Any theories?

**Comment by jasoncoon** [comment]
So the water pattern (and I assume fire as well?) work fine at 300 LEDs but not 470?

FYI, if a specific pattern is causing a reset loop, re-uploading the same sketch won't help since it loads the current pattern index from EEPROM.  You can comment out the code that loads setting from EEPROM and re-upload to work around it.  I should add code to detect reset loops and automatically skip loading settings, set brightness very low, etc.

**Comment by coopooc** [comment]
Huh, I never would have guessed that but it certainly fits the situation. I thought I completely reset the EEPROM with another sketch designed to....fully flush the EEPROM but it must not have worked completely. I'm not sure I have the chops to find the specific code that loads the settings from EEPROM but I'll give it a shot. I'm thinking another option would be to lower the LED count, change the pattern via the web interface and then raise the LED count again. Then I can comment out the offending patterns. 

Thanks, this gives me a place to start.

**Comment by jasoncoon** [comment]
I hid the code that loads settings from EEPROM in a function called, wait for it, loadSettings.  :)

Not sure what's happening.  I don't see anything in the water (or fire) patterns that would cause problems with 470 LEDs but not 300.

**Comment by coopooc** [comment]
I mean, why would you name it something so confusing?? ; ) I commented that out but it had pulled out of the loop after lowering the count and changing the setting in the web interface manually. It was the water pattern. No idea why but after commenting water (and fire) out and bumping the LED count back to the full strand I have had no problems...knock on wood. Just in time for Halloween, thanks again!
