### ISSUE TITLE
Very slow opening

### ISSUE THREAD

**Issue by RisinT96** [jasoncoon/esp8266-fastled-webserver#41]
Hello, I'm trying to use your code on my WeMos D1 R2, but it takes very long to load the website from a computer on the network, Chrome timed it at 17.37 seconds, see screenshot.

It seems to take very long to send the scripts.js and styles.css files.
Any ideas how to speed up the process/ source of slowdown?
![capture](https://user-images.githubusercontent.com/21155265/32017068-45b4dabe-b9ce-11e7-9cf6-ee43d3441ae4.JPG)

Takes 7.89s for the styles.css and 8.06s for scripts.js.
(ESP is connected to a wireless router and the PC is connected via LAN to the same router)
Thanks.

**Comment by jasoncoon** [comment]
Yeah, the ESP8266 is not a very fast web server.  Try out the v1.1 branch, which defaults to requesting the CSS and JS from much faster CDN servers.  Alternatively, try changing/adding the `max-age` parameter of the `server.serveStatic` calls in setup, which is the number of seconds the browser should cache the files.
