### ISSUE TITLE
Adding effects to use

### ISSUE THREAD

**Issue by hunttolby** [jasoncoon/esp8266-fastled-webserver#44]
Hey i was wondering how simple it would be to add effects to this. i wanted to use some of the effects i found on this website.

https://www.tweaking4all.com/hardware/arduino/adruino-led-strip-effects/

Thanks

**Comment by jasoncoon** [comment]
I find it fairly simple.  Just add a new function that draws one frame, without using any delays, like rainbow(), sinelon(), etc.  Then add that function to the patterns array, along with its name.

Looking at the code for those effects, the biggest problem will likely be replacing all of the delays used with elapsed millis timers.  If your effect function uses delays, the ESP8266 webserver can't respond to requests.

**Comment by hunttolby** [comment]
switching them to something like this? 

http://www.thearduinomakerman.info/blog/2016/4/8/tutorial-delay-vs-timer

**Comment by hunttolby** [comment]
I guess i am just stuck on how to use it as a speed delay like in this source code from the led strip effects.

`void theaterChase(byte red, byte green, byte blue) {
  elapsedMillis timeElapsed;
  for (int j=0; j<10; j++) {  //do 10 cycles of chasing
    for (int q=0; q < 3; q++) {
      for (int i=0; i < NUM_LEDS; i=i+3) {
        setPixel(i+q, red, green, blue);    //turn every third pixel on
      }
      showStrip();
     //this is where i am stuck and where the delay is originally as a "speed" delay
      if(timeElapsed > 50) {
        
        timeElapsed = 0
      }
     
      for (int i=0; i < NUM_LEDS; i=i+3) {
        setPixel(i+q, 0,0,0);        //turn every third pixel off
      }
    }
  }
}`

sorry for bothering but thanks for the help!

**Comment by Tecky10** [comment]
Hi, did you manage it? I would do the same with the "theaterChaseRainbow" from this Side: https://www.tweaking4all.com/hardware/arduino/adruino-led-strip-effects/#LEDStripEffectTheatreChaseRainbow

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
