### ISSUE TITLE
Getting a few errors.

### ISSUE THREAD

**Issue by hunttolby** [jasoncoon/esp8266-fastled-webserver#46]
I have the exact same code and havent changed anything but when i start up the server i get the error of
"pm open, type:2 0"
I also receive an error of
"Not Found : /"
when I put in the ip address to access the server.

**Comment by jasoncoon** [comment]
Sorry for the extremely delayed response.  Have you tried it lately?  Using the latest code from the master branch?  Followed the directions in the readme to upload the web app files to SPIFFS on the ESP8266?

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
