### ISSUE TITLE
Got Following Error now

### ISSUE THREAD

**Issue by Beliar-666** [jasoncoon/esp8266-fastled-webserver#49]
C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h:181:3: error: 'results' was not declared in this scope

   results.value = 0;

**Comment by Beliar-666** [comment]
Hello, its 1.8.3

Whole error:

`In file included from I:\Users\MatzeB\Documents\Arduino\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:0:

I:\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006

 #    pragma message "FastLED version 3.001.006"

                     ^

In file included from I:\Arduino\libraries\FastLED/FastLED.h:68:0,

                 from I:\Users\MatzeB\Documents\Arduino\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

I:\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from I:\Users\MatzeB\Documents\Arduino\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:36:0:

C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h: In function 'long unsigned int decodeIRCode()':

C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h:179:3: error: 'decode_results' was not declared in this scope

   decode_results results;

   ^

C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h:179:18: error: expected ';' before 'results'

   decode_results results;

                  ^

C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h:181:3: error: 'results' was not declared in this scope

   results.value = 0;

   ^

C:\Users\MatzeB\AppData\Local\Temp\arduino_build_722479\sketch\Commands.h:184:7: error: 'irReceiver' was not declared in this scope

   if (irReceiver.decode(&results)) {`

**Comment by Blink515** [comment]
Did you install [this ](https://github.com/sebastienwarin/IRremoteESP8266)IR library?

**Comment by Beliar-666** [comment]
Wuah... My fault. commented IR out, cause i will not use it. This was the whole error. 

I did this cause i got an error from IR library first, but there i hadnt it installed. 

No it works fine. But i have some Flickering...

**Comment by Beliar-666** [comment]
Thx. This helps.

**Comment by tstill88** [comment]
Hi, im getting a similar error but i do have the IR Library installed.

Arduino: 1.8.2 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 9600"

In file included from C:\Users\Administrator\Downloads\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:23:0:

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.001

 #    pragma message "FastLED version 3.002.001"

                     ^

In file included from C:\Users\Administrator\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from C:\Users\Administrator\Downloads\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:23:

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\Administrator\Documents\Arduino\libraries\FastLED/FastLED.h:48:0,

                 from C:\Users\Administrator\Downloads\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:23:

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/fastpin.h: In instantiation of 'class FastPin<14u>':

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<14, 26, 26, 52, (EOrder)10u, 0, false, 50>'

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/chipsets.h:460:7:   required from 'class WS2811Controller800Khz<14u, (EOrder)10u>'

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/FastLED.h:108:52:   required from 'class WS2811<14u, (EOrder)10u>'

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/FastLED.h:295:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2811; unsigned char DATA_PIN = 14u; EOrder RGB_ORDER = (EOrder)10u]'

C:\Users\Administrator\Downloads\esp8266-fastled-webserver-master\esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:225:66:   required from here

C:\Users\Administrator\Documents\Arduino\libraries\FastLED/fastpin.h:207:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by jasoncoon** [comment]
Try changing the DATA_PIN.  If it's currently set to D5, try just 5.

**Comment by tstill88** [comment]
Sorry mate I should have looked harder it was already mentioned before!
