### ISSUE TITLE
MSGEQ7 patterns / support?

### ISSUE THREAD

**Issue by terrag42** [jasoncoon/esp8266-fastled-webserver#5]
Thanks for creating the slick looking webserver interface!
I was wondering if you have worked on adding patterns or support for the MSGEQ7? The title of the program says "ESP8266 + FastLED + IR Remote + MSGEQ7" but I haven't seen any MSGEQ7 features yet.
Thank you!

**Comment by jasoncoon** [comment]
No problem, glad to share, just do me and the community a favor and post anything cool you create over at the FastLED community on G+: https://plus.google.com/communities/109127054924227823508  :smile:

I started to add support for the MSGEQ7, but ran into some noise problems trying to get it to work with the ESP8266.  This is a pretty good article on using the two together, and hope to get back to it soon: http://www.whatimade.today/graphic-equalizer-using-esp8266-msgeq7-ws2812

Good luck!

**Comment by zombodotcom** [comment]
thanks for creating this! do you think you could add mdns? esp8266mdns ?

**Comment by jasoncoon** [comment]
https://github.com/jasoncoon/esp8266-fastled-audio
