### ISSUE TITLE
How to use it with IFTTT

### ISSUE THREAD

**Issue by mc9625** [jasoncoon/esp8266-fastled-webserver#50]
Hi, I would like to use this project with IFTTT. I think that a POST could actually change, for instance, the pattern, but I'm not sure which syntax should be used. Could you please explain it? Thanks

**Comment by shamanix** [comment]
Hi mc 9625,
maby this will also help you: [Link](https://github.com/jasoncoon/esp8266-fastled-webserver/issues/60)
