### ISSUE TITLE
didnt managed to get ir working

### ISSUE THREAD

**Issue by drc85** [jasoncoon/esp8266-fastled-webserver#51]
hi i wanted to make the christmass tree, but my skills are not enought for the mapping... because i have no more time left till tomorrow.... i wanted to make it simple and i tried this one here...

my problem is
the ir receiver , what pin is pin 12??? arent they supposed to be with a D in front of the number?

`Arduino: 1.8.5 (Windows 10), Board: "WeMos D1 R2 & mini, 160 MHz, 921600, 4M (3M SPIFFS)"

In file included from C:\Users\MCLOW\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:0:

C:\Users\MCLOW\Documents\Arduino\libraries\FastLED-master/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006

 #    pragma message "FastLED version 3.001.006"

                     ^

In file included from C:\Users\MCLOW\Documents\Arduino\libraries\FastLED-master/FastLED.h:68:0,

                 from C:\Users\MCLOW\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:19:

C:\Users\MCLOW\Documents\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

esp8266-fastled-webserver:34: error: 'IRrecv' does not name a type

 IRrecv irReceiver(RECV_PIN);

 ^

In file included from C:\Users\MCLOW\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:36:0:

sketch\Commands.h: In function 'long unsigned int decodeIRCode()':

Commands.h:179: error: 'decode_results' was not declared in this scope

   decode_results results;

   ^

Commands.h:179: error: expected ';' before 'results'

   decode_results results;

                  ^

Commands.h:181: error: 'results' was not declared in this scope

   results.value = 0;

   ^

Commands.h:184: error: 'irReceiver' was not declared in this scope

   if (irReceiver.decode(&results)) {

       ^

C:\Users\MCLOW\Desktop\esp8266-fastled-webserver\esp8266-fastled-webserver.ino: In function 'void setup()':

esp8266-fastled-webserver:118: error: 'irReceiver' was not declared in this scope

   irReceiver.enableIRIn(); // Start the receiver

   ^

exit status 1
'IRrecv' does not name a type

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`

**Comment by per1234** [comment]
See https://github.com/jasoncoon/esp8266-fastled-webserver/issues/47#issuecomment-353717894

Also posted at http://forum.arduino.cc/index.php?topic=518535

**Comment by drc85** [comment]
hi thanks that was me :D 
switching it to the older libary worked perfect :D saved me alot of hustle rewrtitting the code..

**Comment by drc85** [comment]
did u ever updated it to the newer libary? could save some issues for new users :D
