### ISSUE TITLE
Issues with Wemos D1 Mini Lite

### ISSUE THREAD

**Issue by Blink515** [jasoncoon/esp8266-fastled-webserver#52]
First issue is that Spiffs is only 512k on the D1 mini lite.  I managed to get the files small enough by linking to a JQuery and Bootstrap CDN and removing the styles.css file and modifying script.js to only have the necessary functions.   This is obviously not the best solution if using the board in AP mode since it will not be able to serve the files from the internet. 

Second issue is that when trying to control the LEDs using the website nothing happens.  The LEDs initially come on all blue as expected in the setup function but after that they stay blue.  They will not change patterns or turn off.  I did some testing by adding a few Serial.prints in the code and can see the board receiving the correct data.  I also put a Serial.print line in the part of the code that shuts the LEDs off if power == 0.  The line prints in the serial monitor as expected but the LEDs still stay blue.

**Comment by MarcoBoer** [comment]
I think (i had this before) it's a power issue. Take care of proper power.

**Comment by Blink515** [comment]
It's not a power issue.  I'm well versed with using LEDs and the Wemos
boards.  There's something else going on with this lite version of the
Wemos D1 mini.

**Comment by MarcoBoer** [comment]
Did you use the resistor on the data? Because i have different versions of wemos d1 mini and with the first version v1.0 i did not had problems, but v2.0 gave me troubles. I cut out resistor....problem solved.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
