### ISSUE TITLE
controlling more esp devices over the webserver

### ISSUE THREAD

**Issue by drc85** [jasoncoon/esp8266-fastled-webserver#54]
i have  one strade, but im planning on putting up more +  ambilight.
i thought it would be cool to control all of them via ONE webserver.

im new to this but i managed to edit the html file how i want it too look.
im not sure if this would work out... each device button is linked to another esp ip.

should look like this. 
<img src="http://img4host.net/upload/011947445a4a8250e6a15.png" alt=""/>

if this works out my main question is,
is there a way i can import (from a linux pc or openelec nuc) a Hyperion signal for ambilight as a "pattern" called ambilight so i can switch it on off easy + i can controll all of my leds from one place ????

im planning on putting two led lamps (each with a own wemos and fast led webserver) right and left next to my couch... in front there is the tv with ambilight wich also should act as a lamp standalone when tv is out...
the lamps next to the couch also should mirror the left and right side of the tv when i active ambilight on the esp of a lamp... its complicated to explain...

i think everthiyng should work but ambilight is making me crazy...
i want to have controll over all led+ambilight straight over the webserver... 
would be nice if somebody could point me in the right direction or could tell me if this is even possible...

sorry if i ask this here but i really think this is the best webserver i could find online :D:D i love it

**Comment by anarchking** [comment]
This is an awesome idea!!! I to would like to see if this is possible.

**Comment by drc85** [comment]
normal controll for more then one esp is working... i just need to find out how to implement the udp and json server into the sketch :D to get hyperion show up as a pattern...

**Comment by drc85** [comment]
https://hyperion-project.org/threads/hyperion-udp-as-single-device.1097/

it is possible ... but my skills not good im a beginnder :D

**Comment by MarcoBoer** [comment]
I do this with Domoticz. Can make groups with it
![image](https://user-images.githubusercontent.com/12191260/34626645-e3e4b6b0-f25d-11e7-81ed-0cba44053113.png)

**Comment by jordanadania** [comment]
Bump? Anything new on this topic? I need this for my job. Willing to pay.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
