### ISSUE TITLE
Where do I enter wifi credentials in the .ino file?

### ISSUE THREAD

**Issue by bwarman** [jasoncoon/esp8266-fastled-webserver#55]
According to the documentation I need to enter my SSID and password into the INO file before uploading but I see no place to do that. What am I missing?

**Comment by Blink515** [comment]
You will enter your WiFi credentials in file Wifi.h on lines 13 and 14.

**Comment by bwarman** [comment]
Thanks! Documentation should be updated to indicate it's in the wifi.h file and not the .ino file, as is stated in the Installation section.

**Comment by jasoncoon** [comment]
I agree it should be updated.  I'm looking forward to your pull request!  :)
