### ISSUE TITLE
Server freezes/resets when disabling FastLED interrupts

### ISSUE THREAD

**Issue by bwarman** [jasoncoon/esp8266-fastled-webserver#57]
I was having blinking/glitchy LEDs on my strand due to interrupts on my Wemos D1 Mini. Previous issues solved this with

`#define FASTLED_ALLOW_INTERRUPTS 0`

Now the blinking is gone but the server freezes or resets at random intervals. I assume it has to do with watchdog resets but I've been unable to completely diagnose it.

**Comment by anarchking** [comment]
Try WiFi.setSleepMode(WIFI_NONE_SLEEP); at the beginning of setup.

**Comment by bwarman** [comment]
That causes the server to freeze completely and not even serve a page. The serial monitor shows the connection and the browser never loads the page. I've diagnosed it as watchdog timer resets. This is the serial monitor output when it freezes:

`ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v0c897c37
~ld`

It takes a few manual button resets to get the server responding again. That probably has something to do with the dropped connection and not necessarily a bug, so to speak. Seems to be a common ESP8266 problem when disabling interrupts. Any solution?

**Comment by Blink515** [comment]
Remove the Define for disabling interrupts and then add the following:
At the top of your sketch before #include
<https://plus.google.com/s/%23include/posts> "FastLED.h" add:
#define <https://plus.google.com/s/%23define/posts>
FASTLED_INTERRUPT_RETRY_COUNT 0

At the beginning of the setup function add:
WiFi.setSleepMode(WIFI_NONE_SLEEP);

**Comment by Blink515** [comment]
Let's try this again.  Replying through email fudged the post pretty badly.

Remove `#define FASTLED_ALLOW_INTERRUPTS 0`
and replace it with
`#define FASTLED_INTERRUPT_RETRY_COUNT 0`

Keep this at the beginning of the setup function though:
`WiFi.setSleepMode(WIFI_NONE_SLEEP);`

**Comment by bwarman** [comment]
Confirmed fix on my end. Adding:
`#define FASTLED_INTERRUPT_RETRY_COUNT 0`
before 
`#include <FastLED.h>`
and adding:
`WiFi.setSleepMode(WIFI_NONE_SLEEP);`
in setup() fixed my issue. 
No glitching pixels and no watchdog resets. Closing the issue.
