### ISSUE TITLE
How to update wifi credentials

### ISSUE THREAD

**Issue by bwarman** [jasoncoon/esp8266-fastled-webserver#59]
I programmed my esp8266 for another network and have since moved it to the network I want to use it in. It is trying to access a "stored" SSID when it starts up. I've reuploaded everything with the new credentials but it won't take. It's just using the stored one. How do I change the wifi credentials once they've been setup and I'm not at the initial setup network?

**Comment by jasoncoon** [comment]
Hey, sorry, I've been trying to rework the wifi to support wireless configuration.  It may not yet be entirely fully baked.    :)

You can always go back and try the [v1.0 branch](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/v1.0/esp8266-fastled-webserver.ino), which is much simpler.

You should also be able to modify [WiFi.h](https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/WiFi.h#L121-L128) in the master branch to connect using a hard-coded SSID and password:

`WiFi.begin(ssid, password)`

**Comment by bwarman** [comment]
I ended up using esptool to completely erase the ESP8266 memory and then re-uploaded everything from scratch. Not the most efficient way to do it but it worked.
