### ISSUE TITLE
Connected to Wifi and showing as ESP8266-XXXX Wifi the same time

### ISSUE THREAD

**Issue by rudelm** [jasoncoon/esp8266-fastled-webserver#62]
Hi,

I've configured the Wifi in code manually so that the ESP connects immediately to my Wifi. However, its showing at the same time the ESP8266-XXXX Wifi SSID as open Wifi.

Is there a way I can disable the open Access Point so that it only connects to my Wifi? In its current form its open to anyone who connects to the open Wifi and uploads a new firmware OTA so I wish I could at least limit the Web interface only to the connected Wifi.

**Comment by eriktwotoe** [comment]
Same problem here, showing ESP8266-XXX, but also trying to connect to webserver of ip set with sta, or AP only shows, Not Found: /

**Comment by jasoncoon** [comment]
Yeah, sorry about that.  I pushed new wifi code to master that clearly wasn't ready.  I'll work on it as soon as I can.  In the interim, try replacing this line:

https://github.com/jasoncoon/esp8266-fastled-webserver/blob/master/esp8266-fastled-webserver.ino#L246

with this code:

https://github.com/jasoncoon/esp8266-fastled-webserver/blob/v1.0/esp8266-fastled-webserver.ino#L38

and

https://github.com/jasoncoon/esp8266-fastled-webserver/blob/v1.0/esp8266-fastled-webserver.ino#L142-L182

**Comment by rudelm** [comment]
Cool thank you! I've made the changes in the linked PR if you want to merge it back to master.

**Comment by CorpusCallosum** [comment]
Hey guys, as a follow up to this, I noticed that `initializeWiFi();` is still commented out on line 249. Should this be uncommented? Everything seems to be working fine for me now after I uncomment this line. 

BTW thanks for the awesome work, this is great!

**Comment by darktimmy** [comment]
Has the code been fixed? The AP WIFI is not working for me and it will only connect to a designated WIFI network. I have tried turning off the WIFI Network but the Board just keeps trying to connect to it and won't go into AP mode.

**Comment by AlejandroSantosG** [comment]
Hello I have the same problem to connect to AP WiFI, the Board just try to connect to my last WIFI network stored, and won't go into AP mode, I sep up the WIFI network whit my SSID and PASSWORD and get connected immediately,  but I want to connect to AP WIFI mode, will appreciate your help, thanks

**Comment by jasoncoon** [comment]
Try the latest code from master?  I just simplified wi-fi, making AP/STA mode explicit, reverting my attempts at auto-setup.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
