### ISSUE TITLE
TwinkleFOX makes esp8266 rebooting

### ISSUE THREAD

**Issue by croisez** [jasoncoon/esp8266-fastled-webserver#66]
Hello,
your application for the esp8266 is amazing! Wonderfull!
I went through all installation process, the code, the data, etc.
But now, I just have a remaining issue: TwinkleFOX animations just don't work.
All others are ok, but TwinkleFOX
Anything evident that I would have performed to make it work?

**Comment by jasoncoon** [comment]
Thanks!  Fixed: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/04103b80a3daa76429df2fa377875cd4dff826eb

**Comment by croisez** [comment]
thank you for the fix ;-p
