### ISSUE TITLE
Webpage don't render

### ISSUE THREAD

**Issue by albzn540** [jasoncoon/esp8266-fastled-webserver#67]
When connecting with my smartphone it renders this screen
![screenshot](https://i.gyazo.com/44edb54af7de333c4c5a9ad8f8156f3b.png)

Could it be that the files necessary dont get downloaded since I dont have an internet connection?

**Comment by jasoncoon** [comment]
Yeah, if you don't have internet access, you'll need to make sure index.htm uses the local CSS and JS resources.

**Comment by albzn540** [comment]
That's the thing. It is.
Here's a link to the html code. I haven't changed a bit in it.
https://pastebin.com/60gEhVBu

**Comment by jasoncoon** [comment]
Does it work when connecting from a desktop or laptop?

**Comment by albzn540** [comment]
Yes, the page renders nicely from my desktop computer. But it's connected via ethernet cable as well, so it has access to the internet.
However, I could try to access the page from a computer that isn't connected to the internet, and with a clear cache tomorrow. I'll let you know the results.

Also, the page renders partly on my new Samsung, there are only some buttons that won't render. I'll provide you with a screenshot tomorrow as well. (The screenshot I showed earlier was from my old Oneplus one.)

Is there something I could try, or some other piece of information you neen?

**Comment by jasoncoon** [comment]
That makes me think it's using the CDN resources instead of local.  Yeah, definitely open the chrome dev tools, go to the network tab, check 'disable cache', then refresh.  Look where the requests for CSS and JS are going.  Post a screen shot of the details here.

The reason I switched from hosting the resources locally to the CDN is that the ESP8266 is not great at handling multiple simultaneous requests.  Browsers like to request everything all at once, which isn't a problem for most web servers.  I need to investigate loading resources manually in js one at a time.

**Comment by albzn540** [comment]
I see, and yes you were right. It's not using the local resources.
But what I dont understand is that the htm code requesting the external sources is commented out? Why are then the sources requested externally?

I grabbed some screenshots: 
![screenshot](https://i.imgur.com/K9xcBEC.png)
![screenshot](https://i.imgur.com/BZN0UzM.png)

Imgur: https://imgur.com/a/SADKI

**Comment by jasoncoon** [comment]
Look at the source of the index.htm being returned from the esp8266 in the network tab.  If it doesn't match, make sure you upload it to SPIFFS.

I use web sockets to push updates to all connected clients, to keep multiple clients in sync, and to push updates made via IR remote.  So you can press a button on the IR remote and see it update in the web page.

The responses already contain the updated values, and that's used to update the UI.

**Comment by albzn540** [comment]
Damn, I seem to have uploaded the webpage from your other repository with audio-response. Then that's probably the problem.
Ah I see. Is the client dependent on the websocket connection or could one just turn everything regarding websockets off in the arduino-code?

**Comment by jasoncoon** [comment]
No, the client isn't dependent on websockets at all.
