### ISSUE TITLE
No hardware SPI pins defined

### ISSUE THREAD

**Issue by m3phisto23** [jasoncoon/esp8266-fastled-webserver#68]
Hello,

has anyone tried to get this running with a NodeMCU?`

i am seeing "No hardware SPI pins defined.  All SPI access will default to bitbanged output""
according to what i read this fork should help to work around this problem 
https://github.com/coryking/FastLED

but i could not manage to get it working.
(i am no programmer at all - so please excuse me if the answer is something obvious)

thanks for your help

**Comment by jasoncoon** [comment]
That's just a warning.  FastLED doesn't support hardware SPI on the ESP8266, but software SPI works great.

**Comment by m3phisto23** [comment]
ok. then i am doing something very wrong. i do not get any output on my leds
maybe it is a problem with addressing the correct pin, i since i am using the NodeMCU i tried with D4

also i tried the FastLED example FirstLight, it did not work.

FASTLED_ESP8266_NODEMCU_PIN_ORDER did not help.

**Comment by jasoncoon** [comment]
Yeah, look for nodemcu pin mapping.  Might try just 4 instead of D4.

**Comment by m3phisto23** [comment]
YOU ARE THE MAN!!!

it does not make a lot of sense to me, but using 4 instead of D4 works. if i understand the pin mapping correct this should not work. but i am glad it does

**Comment by Niac04** [comment]
i also have the same problem of
 '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  145 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
though i'm using LOLIN(WEMOS) D1 R2 & mini but i'm getting this error is it bad thing or something i can ignore sorry if the qusetion i'm asking is funny but i'm new to all this
