### ISSUE TITLE
ESP01 compatibility?

### ISSUE THREAD

**Issue by kelexel** [jasoncoon/esp8266-fastled-webserver#7]
I'm trying to get the webserver to run on the ESP01 boards.

I have a 6 LEDs strip connected to GPIO2 (WS2811)
Nothing connected (yet) to GPIO0

I managed to easily flash the sketch and the data to the SPIFFS (I had to remove the fonts so the data would not exceed 512ko)

I can connect to the ESP (I am using APMode), and see the HTTP UI.
Everything seems to work in there too (power, colors, refresh...)

But..
No lights coming out of the LEDs :(

In my understanding, the ESP01 needs to have it's pin setup as OUTPUT, which I did just in case in setup(); (but maybe FastLED does it already) using:
`pinMode(DATA_PIN, OUTPUT);`

But still, no luck...

I than followed FastLED ESP8266 notes, and tried each of the three:
`#define FASTLED_ESP8266_RAW_PIN_ORDER`
`#define FASTLED_ESP8266_NODEMCU_PIN_ORDER`
`#define FASTLED_ESP8266_D1_PIN_ORDER`

But yet, again, no luck...

Thus the question, in your opinion, should this be able to run on the ESP01 ?
Am I missing something obvious...?

Many thanks ;)

Ps: for the record, here is the content of my console:
Heap: 39744
Boot Vers: 4
CPU: 80
SDK: 1.5.3(aec24ac9)
Chip ID: 13618501
Flash ID: 1327328
Flash Size: 1048576
Vcc: 65535

FS File: /js/scripts.js, size: 154332
FS File: /css/styles.css, size: 229396
FS File: /favicon.ico, size: 4286
FS File: /images/atom196.png, size: 5469
FS File: /index.htm, size: 5110

Connect to Wi-Fi access point: ESP8266 Thing CD45
and open http://192.168.4.1 in your browser
HTTP server started

**Comment by t-i-g** [comment]
I have just got this running on an ESP01 here so it can work!  
I have it hooked up to some generic ebay 5050 12v led tape (I have used this with the fastled code before and although you can only control the leds in 3 led segments it works fine). 

I didn't make any changes to the code apart from: 

- setting the DATA_PIN to 2 (I have the data line connected to GPIO 2)
- putting in my SSID and wifi key
- setting the NUM_LEDS to 15 (as just testing with a small strip I had lying around).   

I also ditched the fonts directory and gziped the data to save space following your suggestion.

As everything seemed to flash correctly I would try those leds on normal arduino or something to make sure they are working fine.


Rubbish picture of it :
![cwgygvfxuaepn3u jpg large](https://cloud.githubusercontent.com/assets/3252465/20032005/38bb80a4-a379-11e6-90c0-3b29282ab2b5.jpeg)


How my ESP01 is connected:
![led_tape_esp01](https://cloud.githubusercontent.com/assets/3252465/20031995/1398a5fe-a379-11e6-9559-3c47516657e9.jpg)
