### ISSUE TITLE
Final Setup

### ISSUE THREAD

**Issue by DocRock2018** [jasoncoon/esp8266-fastled-webserver#72]
I am on the final step and I'm getting a little confused with the instructions. I am attempting to run an access point and I'm not sure what I should do next to be able to access the web app. I have all the libraries installed. I used the ESP8266 Sketch Data Upload to upload the entire github folder to the SPIFF. Is this correct or should I only be uploading the "data" directory? Secondly should I simply upload the WiFi in the IDE or modify the .h file and upload the entire directory to the SPIFF?

**Comment by anarchking** [comment]
Only upload data folder and compile the .ino file in IDE

**Comment by anarchking** [comment]
Of course after you configure your wifi.h with credentials.

**Comment by DocRock2018** [comment]
Which Sketch should I be uploading to run AP?

**Comment by DocRock2018** [comment]
Thank you so much for your answer. I am one step closer. Now I am getting an error with "debugPrintln undeclared" any insights would be much appreciated.

**Comment by jasoncoon** [comment]
Thanks @anarchking for helping!
