### ISSUE TITLE
Cannot Locate Device on AP or WiFi

### ISSUE THREAD

**Issue by DocRock2018** [jasoncoon/esp8266-fastled-webserver#74]
I have been able to get the code to compile and upload correctly. I have updated the WiFi file with both the AP Password and the WiFi credentials for my home network and I cannot navigate to the web app with either method. I looked at the serial monitor when I load the sketch/reset my Wemos Pro and its produces a string of 8-10 random symbols that do not repeat and each reset just produces a different random set of symbols. 

EDIT: Removed Edit

**Comment by mattncsu** [comment]
The ESP spits out debug messages at 74880 baud.  Change your rate to 74880 to read the messages.

**Comment by jasoncoon** [comment]
Try 115200, which is what is used in setup: `Serial.begin(115200);`

**Comment by DocRock2018** [comment]
Thank you again Jason. 115200 baud was the fix.

**Comment by jasoncoon** [comment]
No problem, glad you got it working!  And many thanks to @mattncsu for jumping in to help!

**Comment by DocRock2018** [comment]
OK so same title but this time I am not finding the device on LAN via Chrome or AP. 

I get This:
"
Heap: 31784
Boot Vers: 31
CPU: 80
SDK: 2.2.1(cfd48f3)
Chip ID: 10448976
Flash ID: 1458376
Flash Size: 4194304
Vcc: 65535


 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset
"

Any help would be much appreciated.
