### ISSUE TITLE
nothing found!!!!

### ISSUE THREAD

**Issue by sumondigi** [jasoncoon/esp8266-fastled-webserver#76]
@jasoncoon 
thanks for sharing such laborious job.
firstly , i was not finding anything even the led also.
then i edit this area from false to true:
`const bool apMode = true; `
got the AP naming : Esp8266 Thing 1E97
it is being connected and pinging on 192.168.4.1 very well.
BUT in browser the 192.168.4.1 shows " Not found: /"
what should I do!!??

**Comment by anarchking** [comment]
Did you use the data upload tool?

**Comment by sumondigi** [comment]
Hi  jasoncoon
it is overwhelming to me that u have replied.
i have seen the 'data upload tool ' after uploading the question.
please don't maind.
thanks..

**Comment by jasoncoon** [comment]
Are your LEDs functioning properly?  Even without the web app, they should work.

Tried opening the browser dev tools and looking at the network tab?  When you click buttons in the web app, you should see network requests being sent from the browser to the ESP8266.

**Comment by anarchking** [comment]
I believe the board you are using is 5v in bout not 5v out for the 5v pin. Check your board diagram

**Comment by sumondigi** [comment]
Hi jasoncoon
good news !! its done!!
because ,i didn't have the idea declaring pin name in code and pin name on board would be different.(u r laughing...) .what a nice job u have done! 
--------------------------i am not good in coding------------------------
I've used this web app whole day long and  i think i need a user manual or your instruction for better performance, causing all Patterns & Palettes are not matching with my 30 led  .
1.tell me how do i turn off the total strip- the power button doesn't work?
2.how much led i can use with this program?
3.is there any dedicated app?
thankssssss

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
