### ISSUE TITLE
cant open http://xxx.xxx.x.xx/simple.htm

### ISSUE THREAD

**Issue by maik-dmxc** [jasoncoon/esp8266-fastled-webserver#77]
the webpage http://xxx.xxx.x.xx/simple.htm only shows 2 buttons
 ( on & off)

> 
`<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ESP8266 + FastLED by Evil Genius Labs</title>

  
  

  
  <link rel="stylesheet" href="css/bootstrap.min.css">

  <link rel="stylesheet" href="css/simple.css">

  <link rel="icon" href="images/atom196.png">
</head>

<body>

  <div id="container" class="container">

    <div style="margin: 5px;">
      <button type="button" class="btn btn-default" id="btnOn">On</button>
      <button type="button" class="btn btn-default" id="btnOff">Off</button>
    </div>

    <div id="patternGrid" class="grid-pattern"></div>

    <div id="colorButtonsRow" class="grid-color"></div>

  </div>

  <div id="templates" style="display: none">

    <div id="colorButtonTemplate" class="grid-item-color"></div>

    <button id="patternButtonTemplate" class="grid-item-pattern btn btn-default"></button>

  </div>

  
  
  
  
  

  
  <script src="js/jquery-3.1.1.min.js"></script>
  <script src="js/bootstrap.min.js"></script>

  <script src="js/simple.js"></script>

</body>

</html>
`

iss this a bug or a feature?

regards maik

**Comment by nekitoss** [comment]
same problem. But according to web-app-simple.png there must be also at least pattern of colors and buttons for effects. Also checked in MAMP server on my PC - same result.

**Comment by anarchking** [comment]
By default the simple.html tries to reach the internet to load this page. You can change it to load locally from the chips spiffs.

**Comment by killrmodz** [comment]
Couldn't get this work, any one have pointers?  I've downloaded the isotop....js and added it into the /js folder.  Still will not populate in either IE or chrome.

**Comment by ArcadeNut** [comment]
I have the same issue.  Using Chrome developer tools , this seems to be the issue.

simple.js:49 Uncaught ReferenceError: ReconnectingWebSocket is not defined
    at simple.js:49

IN simple.js line 49 reads
`var ws = new ReconnectingWebSocket('ws://' + address + ':81/', ['arduino']);`

**Comment by jasoncoon** [comment]
Ah, simple.htm wasn't including that library.  This should fix it: https://github.com/jasoncoon/esp8266-fastled-webserver/commit/757e3b2fd8ba86a17788491478615fc935acf0a0

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
