### ISSUE TITLE
Dosent upload

### ISSUE THREAD

**Issue by Shomlings** [jasoncoon/esp8266-fastled-webserver#78]
Hey! i uploaded this to my ESP8266 and it all worked fine, but when i changed some code and tryed to upload again it just used the old version of the code, i think maybe it didnt overwrite the old code or somthing.. does anyone have a solution to this?

BTW awesome job on the code, i really liked it :D @jasoncoon

**Comment by anarchking** [comment]
Did you make any changes to the data folder if so you should upload it again. What changes did you make? And when was your code originally downloaded?

**Comment by shomlings** [comment]
I did just change SSID and the password

**Comment by anarchking** [comment]
In the wifi.h file?

**Comment by shomlings** [comment]
Yes, but my i think the memoet dont Get overwtited When i upload nei code using the code :/

**Comment by anarchking** [comment]
Your talking about through the credentials web page?

**Comment by shomlings** [comment]
sorry i dont know what happent on the last comment.. 

When i upload my code, nothing changes, i was going to use another wifi and when i uploaded my code, using the tool it was still searching for the last wifi i used.. so the new code wasnt there

**Comment by anarchking** [comment]
You could try wifi.persistent(false); in setup

**Comment by shomlings** [comment]
@anarchking hmm cant find the wifi.persistent line.. what line number is it on?

**Comment by anarchking** [comment]
Youll have to add it at the top of void setup. Its not in there by default. Let me know if this works for you.

**Comment by shomlings** [comment]
It didnt work...

I also noticed that in the console it says:
----------------------------------------------
**[SPIFFS] address: 0x300000**
[SPIFFS] reset  : nodemcu
[SPIFFS] port   : COM6
[SPIFFS] speed  : 115200
----------------------------------------------

 I think the first time i uploaded it was  [SPIFFS] address: 0x000000 

maybe its not writing to the right place in the memory?
