### ISSUE TITLE
How to add a new Pattern like Solid Rainbow but with less colors???

### ISSUE THREAD

**Issue by jemd15** [jasoncoon/esp8266-fastled-webserver#79]
Please, could you tell me how to do that? I know how to setup the websockets and the http get/post requests but I don't know where to add the code of a new pattern

**Comment by FreezyExp** [comment]
in #135 I split the code up a bit, might be easier to get a hang of it.

Patterns are added to the Patter list, using a string name and a function, the string is shown in the browser, the pattern is in the function you specify.

See FastLed documentation or look at the other pattern functions to get a sense of what you can do.

Just like the FastLed DemoReel100, every pattern is called repeatedly, so if you think about how it needs to change the colors, there should be no need to write your own loops or adding delays.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
