### ISSUE TITLE
mDNS Support

### ISSUE THREAD

**Issue by zombodotcom** [jasoncoon/esp8266-fastled-webserver#8]
Hey, Love the project, do you think you could add mDNS support?

**Comment by jasoncoon** [comment]
I haven't had a very good experience with mDNS on the ESP8266.  I don't have any Macs, so I installed the Bonjour service for Windows.  mDNS requests take 10x longer than just using the IP.  I won't be adding it, but it looks like it'd only take a few lines to add it https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino
