### ISSUE TITLE
Cannnot start AP Mode

### ISSUE THREAD

**Issue by apristel** [jasoncoon/esp8266-fastled-webserver#81]
How does one start AP mode if there is not the normal WiFi network around to connect to?

I see where you can change the name of the AP network, other than that, it will just try to connect and reconnect to the network that was originally setup in wifi.h.

Not sure if this is the correct place to be asking this, so please forgive me.

--apristel--

**Comment by jasoncoon** [comment]
Sorry, I hope to investigate this and other issues soon.

**Comment by jasoncoon** [comment]
Try the latest code from master?  I just simplified wi-fi, making AP/STA mode explicit, reverting my attempts at auto-setup.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
