### ISSUE TITLE
Can't set Wi-Fi SSID and Password

### ISSUE THREAD

**Issue by SFoskett** [jasoncoon/esp8266-fastled-webserver#82]
My ESP8266 is in AP mode and working great. I am trying to add it to my wifi network and there's an error...

I click on Wi-Fi in the menu bar, enter the SSID and Password, click Connect, and get the following error:
`Not found: /wifi`

Looks like this refers to this line:
`<form class="form-horizontal" id="form" action="/wifi" method="post">`

Any ideas?

**Comment by jasoncoon** [comment]
Sorry, I hope to investigate this and other issues soon.

**Comment by jasoncoon** [comment]
Try the latest code from master?  I just simplified wi-fi, making AP/STA mode explicit, reverting my attempts at auto-setup.

**Comment by teaker** [comment]
Encountering the same issue.  SFoskett, did you ever get this resolved?

**Comment by teaker** [comment]
I ended up just using https://github.com/tzapu/WiFiManager as a workaround.  It is a nice little library.

**Comment by tihoangyeudau** [comment]
but when you use customstaticip with wifmanager development, you cant start web page

**Comment by HugoBalder** [comment]
Hi all, will there be a fix or enhancement to the WIFI page ?
Would be cool if i enter the credentials, Connect and the values are stored either in the SPIFFS or EEPROM ?
I love this software and build already 2 of them for 2 of my sons with a Wemos D1 Mini Pro and they use it every day :)

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
