### ISSUE TITLE
Do not get a DHCP address in AP mode

### ISSUE THREAD

**Issue by traubsi** [jasoncoon/esp8266-fastled-webserver#83]
When I run the ESP8266 in client mode everything works without problems.
When I use the AP mode I see the configured SSID and can also connect to the WLAN.
After the connection I get no DHCP address.

If I give my WLAN interface manually the IP address (192.168.4.10) then I also reach the FastLED web interface.
If I upload a Wifi AP Mode Example Sketch, I get an IP address as desired.

I use an ESP8266 nodeMCU  1.0 Board with ESP-12E WLAN Module.

Thanx 4 Help!

**Comment by dudesky71** [comment]
This works for me just fine. Try rebooting your client device or shutting the wifi off then back on. Sometimes mine is finicky but it does work.

**Comment by jasoncoon** [comment]
Sorry, I hope to investigate this and other issues soon.

**Comment by jasoncoon** [comment]
Try the latest code from master?  I just simplified wi-fi, making AP/STA mode explicit, reverting my attempts at auto-setup.

**Comment by dudesky71** [comment]
Jason, are you saying the latest code from master only works if you don’t use WiFi manager and hard set WiFi credentials?

**Comment by dudesky71** [comment]
Jason,

I get the following error when I compile “WiFiAPPSK” was not declared in this scope. I made the Secrets.h header file.

**Comment by dudesky71** [comment]
Never mind... it was commented out in the header :) Do I have to use pin D5? Did you switch to DMA based model to eliminate the glitching?

**Comment by jasoncoon** [comment]
:)

No, use whatever pin you actually have wired up.  I didn't switch to DMA or anything, FastLED handles all of that.  I just simplified and updated master to what is currently working for me.

**Comment by dudesky71** [comment]
I got it running. It looks like anything with twinkles makes it glitch. Completely new SPIFFS upload. Tried in AP mode and standard with 128 LEDS on GPIO 5. Its way better but still glitches. Anything I could try?

**Comment by jasoncoon** [comment]
OK, in loop(), try replacing

`FastLED.delay(1000 / FRAMES_PER_SECOND)`

with 

`delay(1000 / FRAMES_PER_SECOND)`

If that doesn't work, also try reducing FRAMES_PER_SECOND from 120 to 60.

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
