### ISSUE TITLE
how to use with websockets

### ISSUE THREAD

**Issue by byedu27** [jasoncoon/esp8266-fastled-webserver#89]
hello, I'm trying to control it using wscat but I do not know what command to put in to make it go down for example.

**Comment by jasoncoon** [comment]
Hey, websockets are not currently used for control, only for providing feedback/update notifications to the web client(s).

You'll need to ensure websockets are enabled (they're currently commented out on master), and then add code to `webSocketEvent` to handle incoming messages.
