### ISSUE TITLE
Random Resets and WiFi Disconnections on NodeMCU

### ISSUE THREAD

**Issue by KitsuneFox94** [jasoncoon/esp8266-fastled-webserver#91]
Hello,

I'm using this with a NodeMCU V3 to run a 144-LED Strip inside my PC case, it's been running great with almost no issues at all for like 3 days until today I noticed the NodeMCU keeps resetting itself randomly and sometimes it even prevents me from connecting to its network (I'm running it in AP Mode)

Apparently, it seems my board runs very hot when that problem happens, so I'm wondering if my board is defective? or should I need to use a resistor/capacitor between the GPIO pin and the Data line on the strip? or is it probably a software problem? Any help is appreciated, thank you in advance!

**Comment by KitsuneFox94** [comment]
My apologies, nevermind. Turned out it was a problem on my part that one of the +5V cables wasn't plugged in properly so it caused the board to randomly resets. Everything is working like a charm again!

**Comment by jasoncoon** [comment]
Hey, sorry for the delayed response.  Glad you got it working!
