### ISSUE TITLE
Rainbow and others...

### ISSUE THREAD

**Issue by killrmodz** [jasoncoon/esp8266-fastled-webserver#93]
Speed doesn't seem to change for rainbow and other animations.  Is this by design?

**Comment by killrmodz** [comment]
This will control your rainbow speed through the webpage.

uint8_t thishue = beat8(speed); 
  fill_rainbow( leds, NUM_LEDS,thishue, 255 / NUM_LEDS);

**Comment by pinq-** [comment]
Same here, I don't see any effect when changing the speed value.  I run wemos d1 mini ja ws2811 lights

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.

Note: The UI recently was updated to show the sections.  Most sections apply to only a single effect type.  Yes, this is not clear, but hopefully at least showing sections between the settings can help make some sense of it all....
