### ISSUE TITLE
Sample sketch for IR only?

### ISSUE THREAD

**Issue by Gomezzzzz** [jasoncoon/esp8266-fastled-webserver#96]
Hello! 
I want to use IR + fastled only, without webserver.

I think I need to uncomment lines
```
#define FASTLED_ALLOW_INTERRUPTS 1
#define INTERRUPT_THRESHOLD 1
```
And what about
`#define FASTLED_INTERRUPT_RETRY_COUNT 0  `
?

**Comment by henrygab** [comment]
Closing due to >1 year inactivity.
