### ISSUE TITLE
Wifi not connecting

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp8266-fastled-webserver#97]
Any ideas why my serial monitor stops at:

Heap: 45984
Boot Vers: 31
CPU: 80
SDK: 2.2.1(cfd48f3)
Chip ID: 6906628
Flash ID: 1458208
Flash Size: 4194304
Vcc: 65535

scandone
state: 0 -> 2 (b0)
FS File: /js/scripts.js, size: 155046
FS File: /fonts/glyphico.eot, size: 20127
state: 2 -> 3 (0)
FS File: /favicon.ico, size: 4286
FS File: /fonts/glyphico.svg, size: 108738
FS File: /fonts/glyphico.ttf, size: 45404
FS

I am using ESP8266 NodeMCU-12e

**Comment by jordanadania** [comment]
UPDATE:

Heap: 45984
Boot Vers: 31
CPU: 80
SDK: 2.2.1(cfd48f3)
Chip ID: 6906628
Flash ID: 1458208
Flash Size: 4194304
Vcc: 65535

scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
FS File: /css/styles.css, size: 229396
FS File: /favicon.ico, size: 4286
FS File: /fonts/glyphico.eot, size: 20127
FS File: /fonts/glyphico.svg, size: 108738
FS File: /fonts/glyphico.ttf, size: 45404
FS File: /fonts/glyphico.woff, size: 23424
FS File: /fonts/glyphico.woff2, size: 18028
FS File: /images/atom196.png, size: 5469
FS File: /index.htm, size: 5249
FS File: /js/scripts.js, size: 155046

Connecting to This
.......state: 5 -> 2 (2a0)
rm 0
..reconnect
state: 2 -> 0 (0)
.scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 2
cnt 
........state: 5 -> 2 (2a0)
rm 0
..reconnect


Looks like stuff gets weird when it tries to connect to my Wifi named "This".

Any ideas? Please.

**Comment by jordanadania** [comment]
It was a wrong Wifi Password.

Please make fun of me.

**Comment by jasoncoon** [comment]
Glad you got it figured out!  Sorry, I was just getting ready to respond.  :)
