### ISSUE TITLE
cant compile the sketch

### ISSUE THREAD

**Issue by Ermesg** [jasoncoon/esp8266-fastled-webserver#98]
Hi thanks for this project. But I cant compile and getting error.

                  `n file included from 
     /var/folders/_c/q05d0w3n2l9947rbc_wpcrmh0000gn/T/arduino_modified_sketch_781856/esp8266- 
     fastled-webserver.ino:23:0:
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/FastLED.h:14:21: note: #pragma  
     message: FastLED version 3.002.001
      #    pragma message "FastLED version 3.002.001"
                     ^
      In file included from /Users/ERMES/Documents/Arduino/libraries/FastLED-master/FastLED.h:65:0,
                 from 
     /var/folders/_c/q05d0w3n2l9947rbc_wpcrmh0000gn/T/arduino_modified_sketch_781856/esp8266- 
     fastled-webserver.ino:23:
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/fastspi.h:110:23: note: #pragma 
     message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
     pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
     /var/folders/_c/q05d0w3n2l9947rbc_wpcrmh0000gn/T/arduino_modified_sketch_781856/esp8266- 
     fastled-webserver.ino: In function 'void setup()':
     esp8266-fastled-webserver:287: error: 'WiFiAPPSK' was not declared in this scope
     WiFi.softAP(AP_NameChar, WiFiAPPSK);
                              ^
     esp8266-fastled-webserver:295: error: 'ssid' was not declared in this scope
     Serial.printf("Connecting to %s\n", ssid);
                                         ^
       esp8266-fastled-webserver:297: error: 'password' was not declared in this scope
       WiFi.begin(ssid, password);
                        ^
      In file included from /Users/ERMES/Documents/Arduino/libraries/FastLED-master/FastLED.h:48:0,
                 from 
     /var/folders/_c/q05d0w3n2l9947rbc_wpcrmh0000gn/T/arduino_modified_sketch_781856/esp8266- 
     fastled-webserver.ino:23:
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/fastpin.h: In instantiation of 'class 
     FastPin<14u>':
      /Users/ERMES/Documents/Arduino/libraries/FastLED- 
      master/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class 
      ClocklessController<14, 52, 52, 103, (EOrder)10u, 0, false, 50>'
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/chipsets.h:482:7:   required from 'class 
     WS2811Controller800Khz<14u, (EOrder)10u>'
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/FastLED.h:108:52:   required from 
     'class WS2811<14u, (EOrder)10u>'
      /Users/ERMES/Documents/Arduino/libraries/FastLED-master/FastLED.h:295:39:   required from 
    'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2811; unsigned 
     char DATA_PIN = 14u; EOrder RGB_ORDER = (EOrder)10u]'
     /var/folders/_c/q05d0w3n2l9947rbc_wpcrmh0000gn/T/arduino_modified_sketch_781856/esp8266- 
     fastled-webserver.ino:225:66:   required from here
     /Users/ERMES/Documents/Arduino/libraries/FastLED-master/fastpin.h:207:2: error: static assertion 
     failed: Invalid pin specified
     static_assert(validpin(), "Invalid pin specified");
     ^
     exit status 1
    'WiFiAPPSK' was not declared in this scope

**Comment by jordanadania** [comment]
Did you create the secret.h file? Or did you uncomment the ssid and password variables?

I believe either solutions should work for you.

**Comment by jordanadania** [comment]
What chip are you using and does your Device Manager recognize the COM port?
